### ISSUE TITLE
SAP Install

### ISSUE THREAD

**Issue by JacksonR4All** [SAP/macOS-enterprise-privileges#102]
Hello,

I am trying to display the app through JAMF, I followed https://derflounder.wordpress.com/2022/04/20/building-a-privileges-installer-package-using-autopkg/ and created the package and deployed the app through JAMF, but even with just running the application from the autopkg folder on both my Sonoma (14.5.0) and my Ventura(13.6.7), as an admin it works fine, and will demote the user, but as the standard user i get the following when I try to run the app:
![Screenshot 2024-06-09 at 8 43 23 PM](https://github.com/SAP/macOS-enterprise-privileges/assets/132100770/13dde81a-0c41-4d4c-a337-b9495c054594)

I assume this is related to the helper tool, which i can see is in the PrivilegedHelperTools folder, I have been trying to resolve the issue, even trying the proposed chmod changes in the closed section and even checked on Slack, but I have been unable to get the software to operate as intended.

**Comment by mthielemann** [comment]
We'll provide a package for the upcoming version 2.0.0, which will be available later this year. Maybe this helps.
