### ISSUE TITLE
Reason Required max char limit

### ISSUE THREAD

**Issue by madisettisunil** [SAP/macOS-enterprise-privileges#103]
Hi,
First of all really great job with the tool, we love it. can the reason required bumped unto 256 please ? it does say in the documentation that 100 is the max. 

Thank you
Sunil

**Comment by mthielemann** [comment]
You can change the maximum by using a configuration profile.

**Comment by madisettisunil** [comment]
`Key: ReasonMaxLength

Available for: Privileges 1.5.3 and later.

Value: Integer

Note: This must be a positive value below 100.

If the ReasonRequired key's value is set to true, this optional key specifies the maximum number of characters the user can enter as the reason for becoming an admin. If not set, the value defaults to 100.

If a value of greater than 100 is specified or if the ReasonMaxLength key is set to a value less than or equal to the value set for the ReasonMinLength key's value, the value of the ReasonMaxLength key is set to the default value of 100.`

**Comment by mthielemann** [comment]
Could you please explain why the 100 character limit it not sufficient for your environment? Thanks.
