### ISSUE TITLE
Provide reason to PrivilegesCli --add

### ISSUE THREAD

**Issue by onlywei** [SAP/macOS-enterprise-privileges#104]
Right now, when using `PrivilegesCli --add`, it prompts the user for the reason for needing admin rights. Our organization sets this to need at least 10 characters.

I want to provide this reason in a single line without prompting the user. Something like:

```
PrivilegesCli --add "this is my reason"
```

Is this possible?

**Comment by mthielemann** [comment]
This is not possible at the moment.
