### ISSUE TITLE
macOS 15 Dock Tile privileges

### ISSUE THREAD

**Issue by precursorca** [SAP/macOS-enterprise-privileges#112]
macOS Sequoia extends background task management to also affect Dock tile extensions. 
I think if you want the end user to not be able to turn off the Privileges app Dock functionality you will have to supply a com.apple.servicemanagement profile via MDM.

The wiki documentation on managing Privileges via MDM profile should therefore be ammended to include this information and perhaps an example profile.

**Comment by mthielemann** [comment]
Is there any official documentation from Apple for this? Privileges does not even show up in the Login Items so I wonder how people could deactivate the Dock Tile plugin.

**Comment by mthielemann** [comment]
I see. Ok, thanks for pointing that out. We're currently working on the documentation for Privileges 2, and while it wouldn't be a problem for a user to disable the Dock Tile plugin for Privileges 2 (because it doesn't contain much functionality anymore), we'll still mention it. Thanks a lot!
