### ISSUE TITLE
[Privileges 2] - Unable to toggle Privileges when Config Profile been deployed

### ISSUE THREAD

**Issue by msanftenberg** [SAP/macOS-enterprise-privileges#113]
When we install the sample configuration profile from within the resources folder and modify this to our needs the expected changes are not happening.
When the profile is been deployed the "Request Privileges" is been grayed out. As soon as the profile is going to be removed "Request Privileges" is available and Privileges can be switched.

**Comment by aduffner** [comment]
Hi @msanftenberg, can you please post your changes to the mobileconfig as code?

**Comment by msanftenberg** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">

<plist version="1.0">
<dict>
	<key>PayloadContent</key>
	<array>
		<dict>
			<key>PayloadContent</key>
			<dict>
				<key>corp.sap.privileges</key>
				<dict>
					<key>Forced</key>
					<array>
						<dict>
							<key>mcx_preference_settings</key>
							<dict>

								<key>ExpirationIntervalMax</key>
								<integer>15</integer>

								<key>EnforcePrivileges</key>
								<string>user</string>

                                <key>RequireAuthentication</key>
                                <true/>

                                <key>AllowCLIBiometricAuthentication</key>
                                <true/>

                                <key>RevokePrivilegesAtLogin</key>
                                <true/>

                                <key>HideOtherWindows</key>
                                <false/>

								<key>ReasonRequired</key>
								<true/>

                                <key>ReasonMinLength</key>
								<integer>20</integer>

                                <key>ReasonMaxLength</key>
                                <integer>50</integer>

                                <key>ReasonPresetList</key>
								<array>

									<dict>
										<key>de</key>
										<string>Um Software zu installieren</string>
										<key>en</key>
										<string>For installing software</string>
										<key>es</key>
										<string>Para la instalación de software</string>
										<key>it</key>
										<string>Per l'installazione del software</string>
										<key>default</key>
										<string>For installing software</string>
									</dict>

								</array>
								
							</dict>
						</dict>
					</array>
				</dict>
			</dict>
			<key>PayloadDescription</key>
			<string/>
			<key>PayloadDisplayName</key>
			<string>Privileges configuration</string>
			<key>PayloadEnabled</key>
			<true/>
			<key>PayloadIdentifier</key>
			<string>com.apple.ManagedClient.preferences.36132147-235E-4663-ADA8-2664C67C4DD2</string>
			<key>PayloadOrganization</key>
			<string>SAP SE</string>
			<key>PayloadType</key>
			<string>com.apple.ManagedClient.preferences</string>
			<key>PayloadUUID</key>
			<string>36132147-235E-4663-ADA8-2664C67C4DD2</string>
			<key>PayloadVersion</key>
			<integer>1</integer>
		</dict>
	</array>
	<key>PayloadDescription</key>
	<string>Configures the Privileges app.</string>
	<key>PayloadDisplayName</key>
	<string>Privileges configuration</string>
	<key>PayloadEnabled</key>
	<true/>
	<key>PayloadIdentifier</key>
	<string>CF401A42-35CA-4DA6-9123-5A49C87ECB5A</string>
	<key>PayloadOrganization</key>
	<string>SAP SE</string>
	<key>PayloadRemovalDisallowed</key>
	<true/>
	<key>PayloadScope</key>
	<string>System</string>
	<key>PayloadType</key>
	<string>Configuration</string>
	<key>PayloadUUID</key>
	<string>50870D16-7AAD-478B-BFFE-BED09499F7E0</string>
	<key>PayloadVersion</key>
	<integer>1</integer>
</dict>
</plist>
`

**Comment by msanftenberg** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">

<plist version="1.0">
<dict>
	<key>PayloadContent</key>
	<array>
		<dict>
			<key>PayloadContent</key>
			<dict>
				<key>corp.sap.privileges</key>
				<dict>
					<key>Forced</key>
					<array>
						<dict>
							<key>mcx_preference_settings</key>
							<dict>

								<key>ExpirationIntervalMax</key>
								<integer>15</integer>

								<key>EnforcePrivileges</key>
								<string>user</string>

                                <key>RequireAuthentication</key>
                                <true/>

                                <key>AllowCLIBiometricAuthentication</key>
                                <true/>

                                <key>RevokePrivilegesAtLogin</key>
                                <true/>

                                <key>HideOtherWindows</key>
                                <false/>

								<key>ReasonRequired</key>
								<true/>

                                <key>ReasonMinLength</key>
								<integer>20</integer>

                                <key>ReasonMaxLength</key>
                                <integer>50</integer>

                                <key>ReasonPresetList</key>
								<array>

									<dict>
										<key>de</key>
										<string>Um Software zu installieren</string>
										<key>en</key>
										<string>For installing software</string>
										<key>es</key>
										<string>Para la instalación de software</string>
										<key>it</key>
										<string>Per l'installazione del software</string>
										<key>default</key>
										<string>For installing software</string>
									</dict>

								</array>
								
							</dict>
						</dict>
					</array>
				</dict>
			</dict>
			<key>PayloadDescription</key>
			<string/>
			<key>PayloadDisplayName</key>
			<string>Privileges configuration</string>
			<key>PayloadEnabled</key>
			<true/>
			<key>PayloadIdentifier</key>
			<string>com.apple.ManagedClient.preferences.36132147-235E-4663-ADA8-2664C67C4DD2</string>
			<key>PayloadOrganization</key>
			<string>SAP SE</string>
			<key>PayloadType</key>
			<string>com.apple.ManagedClient.preferences</string>
			<key>PayloadUUID</key>
			<string>36132147-235E-4663-ADA8-2664C67C4DD2</string>
			<key>PayloadVersion</key>
			<integer>1</integer>
		</dict>
	</array>
	<key>PayloadDescription</key>
	<string>Configures the Privileges app.</string>
	<key>PayloadDisplayName</key>
	<string>Privileges configuration</string>
	<key>PayloadEnabled</key>
	<true/>
	<key>PayloadIdentifier</key>
	<string>CF401A42-35CA-4DA6-9123-5A49C87ECB5A</string>
	<key>PayloadOrganization</key>
	<string>SAP SE</string>
	<key>PayloadRemovalDisallowed</key>
	<true/>
	<key>PayloadScope</key>
	<string>System</string>
	<key>PayloadType</key>
	<string>Configuration</string>
	<key>PayloadUUID</key>
	<string>50870D16-7AAD-478B-BFFE-BED09499F7E0</string>
	<key>PayloadVersion</key>
	<integer>1</integer>
</dict>
</plist>
`

**Comment by msanftenberg** [comment]
Seems that the Code section seems not to work write. 
Attached is all as TXT.
[Privileges_2-0_Testing.txt](https://github.com/user-attachments/files/17396500/Privileges_2-0_Testing.txt)

**Comment by aduffner** [comment]
@msanftenberg You have configured the `ReasonRequired` and `ReasonMinLength` keys so that the user is forced to enter a reason with a minimum of 20 characters and a maximum of 50 characters according to `ReasonMaxLength`. After entering the reason, the button remains grayed out?

Tip for next time: Code which is multiline needs to be encapsulated by three ` ``` ` before and after ` ``` ` the code.

**Comment by msanftenberg** [comment]
Thanks for the Tip.
I'm not even getting the question to request the admin rights. @
<img width="178" alt="2024-10-16 at 10 09 44" src="https://github.com/user-attachments/assets/b3ec913d-291b-4867-b63a-8b174079d09b">

**Comment by aduffner** [comment]
@msanftenberg  Ah got it, you have set `EnforcePrivileges` to `user`. Just remove this key from your config.

**Comment by msanftenberg** [comment]
Thanks. Even after removal sadly not working. Same as before that I'll can't right click and "Request Privileges"

**Comment by aduffner** [comment]
@msanftenberg Why do you want to right-click? Just left-click as usual and authenticate by fingerprint sensor or password as intended. Have you read the comments in the example profile?

**Comment by msanftenberg** [comment]
I did tried.
If I left click it, I can shortly see that it seems a window opens but nothing then happens.

**Comment by mthielemann** [comment]
@msanftenberg 

```
key: ReasonRequired
value: a boolean
                                    
When set to true, the user must provide a reason for requesting administrator privileges.
The reason is logged. Note that once this option is enabled, privileges cannot be changed
from the Privileges Dock tile menu.
```
