### ISSUE TITLE
[Privileges 2] Standard User after restart, but false dock icon

### ISSUE THREAD

**Issue by aduffner** [SAP/macOS-enterprise-privileges#114]
Tested on:
- macOS 15.0.1 (24A348)
- Privileges Beta 2.0.0 (1781)

After increasing to Admin for 4 hours and a shutdown 2min. after and turn on again I ended up like this:
<img width="292" alt="Bildschirmfoto 2024-10-16 um 10 07 28" src="https://github.com/user-attachments/assets/9688f493-19be-4be5-9b45-b1bf8b1d2bf5">

When I click on the app icon, it offers me to get administrator rights, which seems to be correct. 
However, the dock icon (previous screenshot) should be locked and not unlocked.
<img width="297" alt="Bildschirmfoto 2024-10-16 um 10 08 41" src="https://github.com/user-attachments/assets/8f0c2dc0-6ba2-44e0-b1d2-0f4d1ac069ea">

**Comment by mthielemann** [comment]
@aduffner So you have `Revoke administrator privileges at login` enabled?

**Comment by aduffner** [comment]
@mthielemann Yes `RevokePrivilegesAtLogin` is set to `true`, here is the corresponding configuration:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <!--<key>HideOtherWindows</key>
    <false/>-->
    <key>PostChangeExecutablePath</key>
    <string></string>
    <key>PostChangeActionOnGrantOnly</key>
    <true/>
    <key>ExpirationIntervalMax</key>
    <integer>240</integer>
    <key>RequireAuthentication</key>
    <true/>
    <key>AllowCLIBiometricAuthentication</key>
    <true/>
    <key>RevokePrivilegesAtLogin</key>
    <true/>
    <key>ReasonMinLength</key>
    <integer>20</integer>
    <key>ReasonMaxLength</key>
    <integer>50</integer>
    <key>ReasonRequired</key>
    <true/>
    <key>ReasonPresetList</key>
    <array>
      <dict>
        <key>de</key>
        <string>Um Software zu installieren</string>
        <key>default</key>
        <string>For installing software</string>
      </dict>
      <dict>
        <key>de</key>
        <string>Für Schabernack</string>
        <key>default</key>
        <string>For fun</string>
      </dict>
    </array>
    <key>RemoteLogging</key>
    <dict>
      <key>ServerType</key>
      <string>webhook</string>
      <key>ServerAddress</key>
      <string>https://censored.xx</string>
    </dict>
  </dict>
</plist>
```

**Comment by mthielemann** [comment]
@aduffner Can you reproduce it all the time? I installed your profile, get admin rights for 4 hours, then restart the machine and it works as expected. It reverts admin rights and the Dock icon also reflects this. 🤷🏻‍♂️

**Comment by aduffner** [comment]
@mthielemann No, this time it went from unlocked to locked after about 5 seconds after the restart. 
Maybe it was a one-off behavior. I'll keep an eye on it.
