### ISSUE TITLE
[Privileges 2] Dropdown persistent, but not "Request Privileges" after accessing settings

### ISSUE THREAD

**Issue by aduffner** [SAP/macOS-enterprise-privileges#115]
Tested on:
- macOS 15.0.1 (24A348)
- Privileges Beta 2.0.0 (1781)

Starting Point: Click on the dock icon. 
<img width="297" alt="Bildschirmfoto 2024-10-16 um 09 59 31" src="https://github.com/user-attachments/assets/6ca1d187-0fd7-4e23-aad7-5f5918526eb7">

Choose an dropdown option:
<img width="297" alt="Bildschirmfoto 2024-10-16 um 09 59 51" src="https://github.com/user-attachments/assets/e3e64aad-761b-470e-b969-846a675650ee">

Accessing settings:
<img width="500" alt="Bildschirmfoto 2024-10-16 um 10 00 00" src="https://github.com/user-attachments/assets/037364fc-736e-45fc-84ce-a26670a005a1">

Coming back to the escalation dialog and facing an unecpected greyed out button:
<img width="297" alt="Bildschirmfoto 2024-10-16 um 10 00 09" src="https://github.com/user-attachments/assets/93eefd55-34a4-43e3-b960-91c2c505abd3">

I am able to reproduce this every time at 100% "success" rate.

**Comment by mthielemann** [comment]
@aduffner Thanks for reporting this. Just fixed it. Please test again with the new beta I'll post beginning of next week. Thanks.

**Comment by mthielemann** [comment]
@aduffner The new beta 1787 has just been posted.
