### ISSUE TITLE
[Privileges 2] Layout differs between languages?

### ISSUE THREAD

**Issue by aduffner** [SAP/macOS-enterprise-privileges#119]
Tested on:
- macOS 15.0.1 (24A348)
- Privileges Beta 2.0.0 (1795)

@mthielemann In #116 you posted following screenshot:
<img width="632" alt="Screenshot 2024-10-22 at 16 00 00" src="https://github.com/user-attachments/assets/13547c64-81ec-4884-a498-136866760dbd">

On my computer (language: German) the layout is different - especially the buttons:
Is this intentional or a change made by the swift(ui) handler?

<img width="297" alt="image" src="https://github.com/user-attachments/assets/1fd4f437-3f0d-4d05-b705-d82db88115f5">

**Comment by mthielemann** [comment]
@aduffner Yes, this is automatically done by the system depending on the amount of text.
