### ISSUE TITLE
[Privileges 2] Add Settings to Dock icon context menu

### ISSUE THREAD

**Issue by pryley** [SAP/macOS-enterprise-privileges#120]
I find it confusing when opening Privileges to access the settings. Here is why:

1. If I want to modify the settings, chances are good that I don't intend to escalate privileges and I am only opening Privileges to change the settings.
2. Once I close the settings, Privileges gains focus and the "Request/Revert Privileges" button is highlighted.
3. For a split second I'm wondering why it's asking me to do so until I remember that I opened it to change the settings. This is a moment of UI confusion that is unnecessary.

I suggest the following:

1. Close the Privileges window when opening the Settings (and don't reopen it when closing the settings window).
2. Add a "Settings" entry to the Dock icon context menu:
<img width="321" alt="image" src="https://github.com/user-attachments/assets/44c52e86-8ea3-49c6-8b05-ca40d3c5ced8">

**Comment by mthielemann** [comment]
@pryley Thanks for reporting this. I have added this to our backlog for a future version of Privileges.

**Comment by mthielemann** [comment]
This feature has been added to build 1809.
