### ISSUE TITLE
[Privileges 2] Inform the user which settings are managed - Enhancement?

### ISSUE THREAD

**Issue by aduffner** [SAP/macOS-enterprise-privileges#121]
Tested on: macOS 15.0.1 (24A348) with Privileges Beta 2.0.0 (1805)

In this view:
<img width="500" alt="Bildschirmfoto 2024-10-24 um 12 25 27" src="https://github.com/user-attachments/assets/fcf3c6bc-5a4e-42fa-acd0-cfda15a7b59b">

A (red) text like in Microsoft Defender would be cool to make it clear to the user which settings they cannot edit.
<img width="800" alt="Bildschirmfoto 2024-10-24 um 12 25 23" src="https://github.com/user-attachments/assets/4c768925-7c02-4509-9e19-7258ae2abb1a">

**Comment by mthielemann** [comment]
@aduffner Sorry, but this is far away from what is standard on macOS. If you look at the System Settings, the managed settings are just disabled. So for a Mac user it should be pretty clear what this means. Not sure why Microsoft implemented this in a way that is far away from what Apple does…?
