### ISSUE TITLE
[Privileges 2] Webhooks: Suggestions

### ISSUE THREAD

**Issue by aduffner** [SAP/macOS-enterprise-privileges#123]
Referencing: macOS 15.0.1 (24A348) with Privileges Beta 2.0.0 (1805)

<img width="981" alt="Bildschirmfoto 2024-10-24 um 18 12 34" src="https://github.com/user-attachments/assets/c1a740d4-a030-4121-9fec-afb01c092441">

Of course Power Automate can give me a date, but it would be easier if the post message included when and how the user terminated their admin rights locally (time expired or self terminated).

```
{
  "admin": false,
  "expires": "<expired date>",
  "machine": "xxx-xxx-xxx-xxx-xxx",
  "reason": "<time ran out/ user gave up>",
  "user": "myusername"
}
```

**Comment by mthielemann** [comment]
@aduffner Good idea but I would not misuse the `expires` field for a timestamp but add an additional `timestamp` field. Would this work for you?

**Comment by mthielemann** [comment]
Starting with build 1813 the JSON looks like this:

```
{
  "admin":true,
  "expires":"2024-10-25T07:24:19Z",
  "machine":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "reason":"",
  "timestamp":"2024-10-25T07:19:19Z",
  "user":"xxxxxxxxx"
}

{
  "admin":false,
  "expires":"",
  "machine":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "reason":"requested by user",
  "timestamp":"2024-10-25T07:19:19Z",
  "user":"xxxxxxxxx"
}

{
  "admin":false,
  "expires":"",
  "machine":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "reason":"privileges expired",
  "timestamp":"2024-10-25T07:19:19Z",
  "user":"xxxxxxxxx"
}
```

In addition to this the regular logging has been changed to this:

```
User xxxxxxxxx now has standard user privileges (requested by user)
User xxxxxxxxx now has standard user privileges (privileges expired)
```

**Comment by aduffner** [comment]
@mthielemann Love it! You have turned my original idea into a holistic approach.

**Comment by aduffner** [comment]
Result/Example 🤩
<img width="613" alt="Bildschirmfoto 2024-10-25 um 10 03 35" src="https://github.com/user-attachments/assets/0d8a8ece-d4d2-4acc-bd99-e962e75a2bff">

Request Body JSON Schema:
```
{
    "type": "object",
    "properties": {
        "admin": {
            "type": "boolean"
        },
        "expires": {
            "type": "string"
        },
        "machine": {
            "type": "string"
        },
        "reason": {
            "type": "string"
        },
        "timestamp": {
            "type": "string"
        },
        "user": {
            "type": "string"
        }
    }
}
```
