### ISSUE TITLE
Please update the supported OS versions in the main README file for the repo

### ISSUE THREAD

**Issue by rtrouton** [SAP/macOS-enterprise-privileges#126]
In the https://github.com/SAP/macOS-enterprise-privileges/blob/main/README.md file, the supported OS versions are listed as follows:

```
Privileges supports the following macOS versions:

macOS 15.x
macOS 14.x
macOS 13.x
macOS 12.x
macOS 11.x
```

[Privileges 2.x](https://github.com/SAP/macOS-enterprise-privileges/releases/tag/2.0.0) appears to support the following OS versions:

````
macOS 15.x
macOS 14.x
macOS 13.x
````

Can the supported OS versions listed in the https://github.com/SAP/macOS-enterprise-privileges/blob/main/README.md file please be  updated to match the OS versions supported by Privileges 2.x?

**Comment by mthielemann** [comment]
@rtrouton Privileges 2 runs on macOS 11 and higher, so the information in the README.md file seems to be correct.

**Comment by rtrouton** [comment]
OK, thank you. I hadn't tested this, so I was going by what was listed on the release page.

**Comment by mthielemann** [comment]
Changed the release page accordingly. Thanks for reporting this.
