### ISSUE TITLE
[Privileges 2.0] Webhook not being sent

### ISSUE THREAD

**Issue by mwmatter** [SAP/macOS-enterprise-privileges#127]
Trying to test the webhook feature of 2.0. I'm using a testing site like: https://webhook-test.com/. I have my configuration profile set like this for the RemoteLogging:

`<key>RemoteLogging</key>
  <true/>
  <key>ServerType</key>
  <string>webhook</string>
  <key>ServerAddress</key>
  <string>https://webhook-test.com/TESTPATHHERE</string>`

I am not seeing anything on the webhook site. Looking at the console logs for the PrivilegesAgent I'm seeing an uncaught exception error.
![Screenshot 2024-11-21 at 11 26 34 AM](https://github.com/user-attachments/assets/dfe8230a-ba79-415b-bc8f-e5678b2ad223)

Not sure if these are related or not to my issue. Let me know if there is any other data I can provide.

**Comment by mthielemann** [comment]
So this is your configuration?

```
<key>RemoteLogging</key> 
<true/>
<key>ServerType</key>
<string>webhook</string>
<key>ServerAddress</key>
<string>https://webhook-test.com/TESTPATHHERE</string>
```

But the value of the RemoteLogging key must be a dictionary and not a boolean. So it must look like this:

```
<key>RemoteLogging</key> 
<dict>
   <key>ServerType</key>
   <string>webhook</string>
   <key>ServerAddress</key>
   <string>https://webhook-test.com/TESTPATHHERE</string>
</dict>
```

Please check the [documentation](https://github.com/SAP/macOS-enterprise-privileges/wiki/Managing-Privileges) for further information on how to set up remote logging. Thanks.

**Comment by mwmatter** [comment]
Ah I don't know how I missed that in the documentation. Thanks!
