### ISSUE TITLE
[Privileges 2] Prompt Appears In Unexpected Locations on Multi-Screen Setups

### ISSUE THREAD

**Issue by rougegoat** [SAP/macOS-enterprise-privileges#128]
While testing Privileges 2.0.0, I noticed that the Request Privileges pop-up window appears in unexpected locations if you attempt to run it from various screens.

**Screen where the dock is:** Appears in the center as expected
**Screen to the left of the one with the dock:** Appears at the left most edge of the screen with the dock on it
**Screen to the right of the one with the dock:** Appears at the right most edge of the screen with the dock on it

Moving the dock to the appropriate screen and trying again does put it back in the center, but I can't be the only one out there who would click on the icon in their dock without first moving it to the screen I was working in last.

**Comment by mthielemann** [comment]
Yes, we aware of this issue but it is related to a bug Apple needs to fix. We already filed a bug report and now need to wait until Apple fixes it.

**Comment by mthielemann** [comment]
@rougegoat I found a workaround that (hopefully) fixes this problem, as I do not think Apple will fix the underlying problem in the near future. Please check again with version 2.1, which I expect to be released in January 2025. Thanks again.

**Comment by mthielemann** [comment]
@rougegoat Could you please test with the [Privileges 2.1 Public Beta](https://github.com/SAP/macOS-enterprise-privileges/discussions/141)? Thanks.

**Comment by mthielemann** [comment]
The underlying issue has been fixed by Apple in the macOS 27 beta.
