### ISSUE TITLE
[Privileges 2] Exclude user(s) from being demoted - "Enhancement"?

### ISSUE THREAD

**Issue by JakoVerstraate** [SAP/macOS-enterprise-privileges#130]
It would be nice to have the possibility to exclude one or more admin-users from being demoted, just like PrivilegesDemoter has. The tekst below was copied from the PD-Wiki.

**excludedAdmins - Type: String, Default Value: [], Required: No**

Enter the usernames of any users that should never be offered demotion by PrivilegesDemoter. Usernames are case sensitive and should be separated by a comma. Example orgAdmin, jamfAdmin

Note: _mbsetupuser and root users are always excluded from demotion.

**Comment by mthielemann** [comment]
Thanks for this feature request. This feature is currently scheduled for version 2.1.

**Comment by JakoVerstraate** [comment]
Nice, thank you!

**Comment by breisig** [comment]
This would be an excellent feature.

**Comment by mthielemann** [comment]
@JakoVerstraate Could you please test with the [Privileges 2.1 Public Beta](https://github.com/SAP/macOS-enterprise-privileges/discussions/141)? Thanks.

**Comment by amirghaliusa** [comment]
@mthielemann I added the new management key "RevokeAtLoginExcludedUsers" to my configuration profile and I listed 2 local admin users but unfortunately, they are still getting demoted while testing with the Privileges_2.1.0b1875 package.
Here's a copy of my plist file:

```typescript
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
		<key>AllowPrivilegeRenewal</key>
                <true/>
                <key>ReasonRequired</key>
		<true/>
                <key>HideSettingsButton</key>
		<true/>
		<key>ReasonMinLength</key>
		<integer>20</integer>
		<key>ReasonMaxLength</key>
		<integer>50</integer>
                <key>ReasonCheckingEnabled</key>
                <true/>
                <key>RequireAuthentication</key>
                <true/>
                <key>AllowCLIBiometricAuthentication</key>
                <true/>
		<key>ExpirationInterval</key>
		<integer>10</integer>
                <key>RevokePrivilegesAtLogin</key>
                <true/>
                <key>RevokeAtLoginExcludedUsers</key>
                                <array>
                                        <string>admin</string>
                                        <string>pctech</string>
                                </array>
</dict>
</plist>
```

**Comment by JakoVerstraate** [comment]
@mthielemann it works almost like it should with 2.1 (1875)!
I used the same config as above (with my own excluded admins), 15 minutes admin-time and _Settings_ enabled.
Is this the right config-profile (with all settings) or am I missing something?

When I log on with one of these excluded admins and click _Settings_, I see 
<img width="491" alt="adminprivileges" src="https://github.com/user-attachments/assets/0e9fff07-e9b2-4d9a-8385-dd557100017e"> (revoking disabled). 
Next time I log in they are still admin.
When I log in with a non-admin-user and check _Settings_ I see 
<img width="491" alt="nonadminprivileges" src="https://github.com/user-attachments/assets/b9294b69-5d96-4283-9870-c11d4f0f94f3"> (revoking enabled)
Next time I log in they are no longer admin

The Renew-function works as expected, I get a notification and when I click _Renew_ the time increases to 15 minutes again
<img width="326" alt="renew2" src="https://github.com/user-attachments/assets/5933e518-d300-4f32-bc49-170568efc39f">

However, there is one thing I'm missing: all users (including excluded-admins) are demoted to standard users. I think excluded-admins should stay admin and not get demoted to standard user.

And another strange thing; when I Enable Privileges, I need to confim I want to be Admin in this screen below
<img width="240" alt="Confirmation" src="https://github.com/user-attachments/assets/312f4237-8343-4ea6-9be4-6eaba961c6f2">

**Comment by mthielemann** [comment]
@JakoVerstraate Don't know which profile you used but the authentication dialog is shown because you obviously set `RequireAuthentication` to `true`. What do you mean with: "all users (including excluded-admins) are demoted to standard users"? If I understand correctly the admins excluded stay admin if they log out and log in again.

**Comment by JakoVerstraate** [comment]
You're right! just swiched set RequireAuthentication to false and the message is gone, sorry!

**Comment by JakoVerstraate** [comment]
and Yes, they stay admin (when I log off and on within 15 minutes)

**Comment by mthielemann** [comment]
and that's what the `RevokeAtLoginExcludedUsers` is used for. only for this.

**Comment by mthielemann** [comment]
So if they request admin rights for a certain time, the rights are still revoked after that time.

**Comment by JakoVerstraate** [comment]
aha, then it works as expected ;-)
However what I meant with this Feature Request is that excluded admins should never be demoted to standard users (just like in PrivilegesDemoter)

**Comment by mthielemann** [comment]
If you create an admin account, the admin rights are never removed. Even if you force removal of the admin rights at login for all other users, you can exclude the admin account using the `RevokeAtLoginExcludedUsers` key and it will stay admin.

**Comment by mthielemann** [comment]
BTW: This is a fundamental difference between Privileges and PrivilegesDemoter. Privileges will not ask you to revoke your admin rights unless you have requested them using Privileges.

**Comment by JakoVerstraate** [comment]
hmmm, my (excluded) admin-user gets reverted to a standard-user after 15 minutes. After logging out and in again or restarting it is still a standard-user.
I'll check all my settings and wipe my test-Mac to make a clean start and will test again

**Comment by mthielemann** [comment]
They will only be reverted if they requested admin privileges using `Privileges`. If you have admin accounts that never used `Privileges`, they will not be reverted.

**Comment by JakoVerstraate** [comment]
Ok, that is _exactly_ what I did to test (use Privileges with an excluded-admin). Thanks for clearing that up!

**Comment by JakoVerstraate** [comment]
Thanks for creating Privileges 2.1 so soon after 2.0. And thanks for your quick replies!

**Comment by mthielemann** [comment]
Thanks for testing and improving the app. 😊

**Comment by mthielemann** [comment]
Can you reproduce this? I've never seen it. When I log in, I get a notification that privileges have been revoked. Just tried this in a vm and also there it works as expected. Really weird.

**Comment by mthielemann** [comment]
If you see the countdown and it asks you to renew privileges, then they definitely haven't revoked. Maybe it would help to check the logs to see what actually happened. You could get admin rights, then log out and log in again and then open the Terminal and use this to get the information: 
```
log show --predicate 'process BEGINSWITH "Privileges" && eventMessage BEGINSWITH "SAPCorp:"' --last 5m
```

**Comment by amirghaliusa** [comment]
@mthielemann I created a new admin user on my test machine and after I logged in for the first time it still demoted my account to a standard user. I had never launched the Privileges app under this account!

**Comment by mthielemann** [comment]
@amirghaliusa What version of Privileges did you use?

**Comment by amirghaliusa** [comment]
> @amirghaliusa What version of Privileges did you use?

@mthielemann I used the latest 2.1 beta version "Privileges_2.1.0b1875.pkg". I'm erasing my test machine now and starting fresh just to make sure I didn't miss something. Thank you!

**Comment by JakoVerstraate** [comment]
@mthielemann Yes, I can reproduce this. Here's what I did:
I used a Jamf Connect created standard user to log on, enabled Privileges, logged out and logged in with the same user. the countdown is there, but I'm no longer admin. In this case I used the Jamf Connect Login screen
![Login_JC](https://github.com/user-attachments/assets/90743c87-a450-47fe-9813-1384628c5fa0)

After that I created a local account, logged in with that account, enabled Privileges, logged out and in again. then I got the same notification you got, and no countdown.

That gave me an idea. I logged on again with my JC created standard user again, enabled Privileges, logged out and logged in with the same user again. Only this time I logged in with the _Local_ (non-JC) login-screen. this time I got the notification and no countdown.

This means my _problem_ is a combination of Privileges and the Jamf Connect Login-screen. When I use the Local (non-JC/Native-Apple-Login) everything behaves as expected.

I can perfectly live with that! the situation I tested is very unlikely to happen for our normal users (only in tests like this)

**Comment by amirghaliusa** [comment]
@mthielemann I started with a fresh install of macOS Sonoma v14.7.1. Installed the same config profile and the latest beta version of Privileges 2.1, same behavior:
The local admin accounts that were originated from an Active Directory authentication were demoted to a standard account as well as my local admin account that gets created as part of my automated enrollment. I did not run the Privileges app under those account.
One thing I noticed that this only occurred after I had logged in as standard user and ran the Privileges app to request admin Privilege.

**Comment by amirghaliusa** [comment]
@mthielemann attached are snippets from the system log as well as a copy of my configuration. Thanks in advance for any insights on this!
[PrivilegesConfiguration.txt](https://github.com/user-attachments/files/18023656/PrivilegesConfiguration.txt)
[sysLog_PrivilegesDaemon.txt](https://github.com/user-attachments/files/18023657/sysLog_PrivilegesDaemon.txt)
[sysLog_Privileges.txt](https://github.com/user-attachments/files/18023658/sysLog_Privileges.txt)

**Comment by mthielemann** [comment]
@amirghaliusa What's your local admin account?

**Comment by amirghaliusa** [comment]
@mthielemann I was testing with 3 admin accounts. "wsd" which is the account that gets created as part of my automated enrollment pre-stage profile with Jamf. "pctech" and "aghali" are also admins. I had never launched Privileges under those accounts. I logged in with my test standard account and used Privileges.

**Comment by mthielemann** [comment]
I did some additional tests yesterday and I was not able to find anything that was not working as expected. Not sure about the accounts Jamf created or AD accounts. This is something I cannot test here.

**Comment by amirghaliusa** [comment]
@mthielemann I can certainly create a new admin account manually and test it out. I will be happy to send the logs after that if you would like?

**Comment by mthielemann** [comment]
@amirghaliusa If you find a reproducible issue with accounts created using the standard macOS procedures, I will try to reproduce it on my end. Thanks.

**Comment by amirghaliusa** [comment]
@mthielemann I manually created a new admin account

<img width="701" alt="Screenshot 2024-12-05 at 10 32 19 AM" src="https://github.com/user-attachments/assets/2a42864d-72f9-48d5-9a4e-ad877e873778">

<img width="464" alt="Screenshot 2024-12-05 at 10 32 11 AM" src="https://github.com/user-attachments/assets/803afaed-30c3-448c-a60a-37251783a903">
<img width="459" alt="Screenshot 2024-12-05 at 10 32 00 AM" src="https://github.com/user-attachments/assets/9d50200c-22af-484e-abff-dff792c9219f">

I made sure that I added the new shortname to my excluded list in the plist

![Screenshot 2024-12-05 at 10 40 38 AM](https://github.com/user-attachments/assets/5b29dad9-9f0a-4896-b58d-acd7ac384499)

I rebooted the machine and Privileges immediately started counting down

<img width="1440" alt="Screenshot 2024-12-05 at 10 37 15 AM" src="https://github.com/user-attachments/assets/1d368420-bc2e-4c85-a6d4-2deb9a30e146">
<img width="403" alt="Screenshot 2024-12-05 at 10 38 14 AM" src="https://github.com/user-attachments/assets/fb6bc4be-b411-4b12-a7f6-a01c0394476b">
<img width="476" alt="Screenshot 2024-12-05 at 10 38 28 AM" src="https://github.com/user-attachments/assets/53def539-6211-49ab-bfaf-a84839b07144">

**Comment by mthielemann** [comment]
@amirghaliusa Could you please test again with [Privileges_2.1.0b1877.pkg.zip](https://github.com/user-attachments/files/18034693/Privileges_2.1.0b1877.pkg.zip)? Thanks.

**Comment by amirghaliusa** [comment]
@mthielemann I have tested with Privileges_2.1.0b1877 and I can confirm that the issue has been resolved! 
Everything is working as expected for ALL accounts; Jamf Pro created, standard macOS manually created accounts as well as for the AD locally created accounts. Thank you so much for your patience and your wellness to continue to test this with me.

**Comment by mthielemann** [comment]
That's great to hear @amirghaliusa. Thanks for finding this and for helping me to improve the app.  I really appreciate it.

**Comment by pcrandom** [comment]
For clarification, even if an admin account is added to the RevokeAtLoginExcludedUsers key, if that account accidentally/unnecessarily runs Privileges, then it will get demoted once time runs out _and_ also if they log out and log back into the Mac?

**Comment by mthielemann** [comment]
If this account runs Privileges to turn the admin account into a standard user account, then yes.

**Comment by pcrandom** [comment]
Sorry, I think my original question was phrased poorly.  I was trying to figure out in what cases RevokeAtLoginExcludedUsers would allow an account to keep admin rights, if it's all cases or only at login.

For example, what if an account that is listed in RevokeAtLoginExcludedUsers is not yet an admin?  If the user then runs Privileges to gain admin rights, will RevokeAtLoginExcludedUsers help prevent removal of admin at the end of the timeout, or only at login?

**Comment by mthielemann** [comment]
`RevokeAtLoginExcludedUsers` only applies to the automatic privilege removal at login. If an account is not an admin and the account is listed in `RevokeAtLoginExcludedUsers` and Privileges is used to gain admin rights, the admin rights will expire after the configured time interval but not at login. If you don't want requested admin rights to expire, configure a timeout of `Never`.
