### ISSUE TITLE
[Privileges 2] Provide more useful logging - Enhancement?

### ISSUE THREAD

**Issue by sgmills** [SAP/macOS-enterprise-privileges#131]
Would love to have a way to save and see logs long term. Could be as simple as a LaunchDaemon, similar to the way Nudge provides extended logging capabilities: https://github.com/macadmins/nudge/blob/main/build_assets/com.github.macadmins.Nudge.logger.plist

**Comment by mthielemann** [comment]
We log everything to syslog and from there you should me able to get back in time. Please explain why this isn’t enough?

**Comment by mthielemann** [comment]
I am not sure if file-based logging is the right way to go. You can collect the log entries you require at any time using the log command and then write it into a file if needed.

**Comment by mthielemann** [comment]
After consulting with Apple engineering, we decided not to implement file-based logging, but to stay with unified logging for flexibility and performance reasons. We believe that a file-based approach would not provide any benefit to our users.
