### ISSUE TITLE
[Privileges 2] Deployment issues with JAMF Pro

### ISSUE THREAD

**Issue by Emod94** [SAP/macOS-enterprise-privileges#132]
Hello everyone,

I am very pleased that Priviliges is now also available in version 2. However, we are struggling with some challenges and I hope you can help a little further here.

1. Deployment via JAMF app catalog
Although I know that you are probably not responsible for this, we have had problems with automatic deployment via JAMF App Catalog since the change from version 1.x to 2.0.0. Maybe you know the right contact person for this, but I am sure that I am not alone with my problem. We have activated the automatic update in the JAMF App Catalog and all our installations are now being migrated to the new version piece by piece. In doing so, the client runs into the error that it cannot establish a connection to the PrivateXPC. This can be read out via the logs. A manual repackaging or reinstallation solves the problem for us.

2. Migration from 1.x to 2.0.0
We have already provided configuration profiles for version 1.x within JAMF Pro. I am currently still struggling a bit to provide a dedicated profile for version 2.x. It is not yet clear to me to what extent version 2.x is compatible with the configuration profiles from 1.x. Whether these may interfere with each other or whether, for example, the profiles from 2.x are backwards compatible with version 1.x. Perhaps you could help a little further here?

3. privileged ignores the configuration profiles
I am currently doubting myself a little. I have built a configuration profile based on your instructions and deployed it on the devices. A few configurations (e.g. LimitedToUser) seem to work. Others like RequireAuthentication, ExpirationIntervalMax or HideSettingsButton are completely ignored. 

I'll send you my config, maybe you have an idea where the error lies?

Thank you for your support!
Dominik

```xml
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>PayloadContent</key>
		<array>
			<dict>
				<key>PayloadContent</key>
				<dict>
					<key>corp.sap.privileges</key>
					<dict>
						<key>Forced</key>
						<array>
							<dict>
								<key>mcx_preference_settings</key>
								<dict>
									<key>LimitToUser</key>
									<string>$EXTENSIONATTRIBUTE_28</string>
									<key>RevokePrivilegesAtLogin</key>
									<true/>
									<key>RequireAuthentication</key>
									<true/>
									<key>AllowCLIBiometricAuthentication</key>
									<true/>
									<key>ExpirationIntervalMax</key>
									<integer>10</integer>
									<key>HideSettingsButton</key>
									<true/>
								</dict>
							</dict>
						</array>
					</dict>
				</dict>
				<key>PayloadDescription</key>
				<string></string>
				<key>PayloadDisplayName</key>
				<string>Privileges configuration</string>
				<key>PayloadEnabled</key>
				<true/>
				<key>PayloadIdentifier</key>
				<string>com.apple.ManagedClient.preferences.36132147-235E-4663-ADA8-2664C67C4DD2</string>
				<key>PayloadOrganization</key>
				<string>SAP SE</string>
				<key>PayloadType</key>
				<string>com.apple.ManagedClient.preferences</string>
				<key>PayloadUUID</key>
				<string>36132147-235E-4663-ADA8-2664C67C4DD2</string>
				<key>PayloadVersion</key>
				<integer>1</integer>
			</dict>
			<dict>
				<key>NotificationSettings</key>
				<array>
					<dict>
						<key>AlertType</key>
						<integer>1</integer>
						<key>BadgesEnabled</key>
						<false/>
						<key>BundleIdentifier</key>
						<string>corp.sap.privileges.agent</string>
						<key>NotificationsEnabled</key>
						<true/>
						<key>ShowInLockScreen</key>
						<false/>
						<key>ShowInNotificationCenter</key>
						<false/>
						<key>SoundsEnabled</key>
						<false/>
					</dict>
				</array>
				<key>PayloadDisplayName</key>
				<string>Notifications Payload</string>
				<key>PayloadIdentifier</key>
				<string>com.apple.notificationsettings.82F3A882-88ED-4B92-8A03-332A9874FDD0</string>
				<key>PayloadOrganization</key>
				<string>SAP SE</string>
				<key>PayloadType</key>
				<string>com.apple.notificationsettings</string>
				<key>PayloadUUID</key>
				<string>82F3A882-88ED-4B92-8A03-332A9874FDD0</string>
				<key>PayloadVersion</key>
				<integer>1</integer>
			</dict>
			<dict>
				<key>PayloadDisplayName</key>
				<string>Service Management Payload</string>
				<key>PayloadIdentifier</key>
				<string>com.apple.servicemanagement.AD895F7A-40F5-454A-B70F-6AA00C3738CF</string>
				<key>PayloadOrganization</key>
				<string>SAP SE</string>
				<key>PayloadType</key>
				<string>com.apple.servicemanagement</string>
				<key>PayloadUUID</key>
				<string>AD895F7A-40F5-454A-B70F-6AA00C3738CF</string>
				<key>PayloadVersion</key>
				<integer>1</integer>
				<key>Rules</key>
				<array>
					<dict>
						<key>Comment</key>
						<string>Approves Privileges and its components</string>
						<key>RuleType</key>
						<string>TeamIdentifier</string>
						<key>RuleValue</key>
						<string>7R5ZEU67FQ</string>
					</dict>
				</array>
			</dict>
		</array>
		<key>PayloadDescription</key>
		<string></string>
		<key>PayloadDisplayName</key>
		<string>SAP Privileges Settings</string>
		<key>PayloadEnabled</key>
		<true/>
		<key>PayloadIdentifier</key>
		<string>408756F8-4B31-4296-84BA-6B4B8A73E085</string>
		<key>PayloadOrganization</key>
		<string>SAP SE</string>
		<key>PayloadRemovalDisallowed</key>
		<true/>
		<key>PayloadScope</key>
		<string>System</string>
		<key>PayloadType</key>
		<string>Configuration</string>
		<key>PayloadUUID</key>
		<string>67923C22-5FCA-4F48-A63C-02A160A9F089</string>
		<key>PayloadVersion</key>
		<integer>1</integer>
	</dict>
</plist>
```

**Comment by naytbrookes** [comment]
You may consider opening a ticket with JAMF about some of the deployment issues.

**Comment by kevinVodi** [comment]
Greetings - we are having escalation failures after Jamf App Installer upgraded our Privileges app to 2.0

We have 2x related profiles - 1x for Privileges and 1x for Demoter

I have unscoped a test computer from these profiles and removed/reinstalled privileges - but it is not allowing for escalation (macOS 15.1.1) after clicking Request
<img width="632" alt="Screenshot 2024-11-25 at 9 26 08 AM" src="https://github.com/user-attachments/assets/9066865c-4ad0-4643-91d3-0f9f35652466">

**Comment by kevinVodi** [comment]
I there any custom schema (JSON) out there for Privileges 2.0 by chance?

**Comment by mthielemann** [comment]
Unfortunately I can't help you with Jamf-related issues. Please reach out to Jamf support and ask them to update their app catalog.

**Comment by Emod94** [comment]
Yes, I understand that. But topic 2 and 3 are not yet JAMF related but are questions about privilege itself?

**Comment by Emod94** [comment]
Hey @mthielemann 

Thanks for the configuration profile and the recommendations. I have installed the following profile on the devices. 
The Privileges app completely ignores everything. In this case, only one profile is provided.

<img width="1322" alt="Screenshot 2024-11-25 at 19 29 30" src="https://github.com/user-attachments/assets/79ae5afd-4dff-425e-a085-b9efda1cde03">

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>Forced</key>
		<array>
			<dict>
				<key>mcx_preference_settings</key>
				<dict>
					<key>LimitToUser</key>
					<string>$EXTENSIONATTRIBUTE_28</string>
					<key>RevokePrivilegesAtLogin</key>
					<true/>
					<key>RequireAuthentication</key>
					<true/>
					<key>AllowCLIBiometricAuthentication</key>
					<true/>
					<key>ExpirationIntervalMax</key>
					<integer>10</integer>
					<key>DockToggleMaxTimeout</key>
					<integer>10</integer>
					<key>HideSettingsButton</key>
					<true/>
				</dict>
			</dict>
		</array>
	</dict>
</plist>
```

**Comment by mthielemann** [comment]
Yes, because it's not a complete profile. I just posted the important part (the Privileges configuration) and removed all the other (but required) stuff.

**Comment by Emod94** [comment]
@mthielemann 

So I'm really sorry now. Maybe I'm just a little confused after all this time. I have now taken exactly one example configuration profile from your repo. Removed the content and added the code you provided. Then deployed and I still get the same messages from the logs as before and the app does nothing at all.

I really don't want to annoy you now. But I'm starting to question my sanity. 😅
This is now in the config profile. Provided for the domain **corp.sap.privileges**

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>PayloadContent</key>
		<array>
			<dict>
				<key>PayloadContent</key>
				<dict>
					<key>corp.sap.privileges</key>
					<dict>
						<key>Forced</key>
						<array>
							<dict>
								<key>mcx_preference_settings </key>
								<dict>
									<key>LimitToUser</key>
									<string>$EXTENSIONATTRIBUTE_28</string>
									<key>RevokePrivilegesAtLogin</key>
									<true/>
									<key>RequireAuthentication</key>
									<true/>
									<key>AllowCLIBiometricAuthentication</key>
									<true/>
									<key>ExpirationIntervalMax</key>
									<integer>10</integer>
									<key>DockToggleMaxTimeout</key>
									<integer>10</integer>
									<key>HideSettingsButton</key>
									<true/>
								</dict>
							</dict>
						</array>
					</dict>
				</dict>
				<key>PayloadDescription</key>
				<string/>
				<key>PayloadDisplayName</key>
				<string>Privileges configuration</string>
				<key>PayloadEnabled</key>
				<true/>
				<key>PayloadIdentifier</key>
				<string>com.apple.ManagedClient.preferences.3F98C2D8-E845-4F59-B447-16AEA78FB584</string>
				<key>PayloadOrganization</key>
				<string>SAP SE</string>
				<key>PayloadType</key>
				<string>com.apple.ManagedClient.preferences</string>
				<key>PayloadUUID</key>
				<string>3F98C2D8-E845-4F59-B447-16AEA78FB584</string>
				<key>PayloadVersion</key>
				<integer>1</integer>
			</dict>
		</array>
		<key>PayloadDescription</key>
		<string>Configures the Privileges app.</string>
		<key>PayloadDisplayName</key>
		<string>Privileges configuration</string>
		<key>PayloadEnabled</key>
		<true/>
		<key>PayloadIdentifier</key>
		<string>5790E5B5-A81D-4E4F-9AB6-6F573CC399DD</string>
		<key>PayloadOrganization</key>
		<string>SAP SE</string>
		<key>PayloadRemovalDisallowed</key>
		<true/>
		<key>PayloadScope</key>
		<string>System</string>
		<key>PayloadType</key>
		<string>Configuration</string>
		<key>PayloadUUID</key>
		<string>19BF1861-0134-4BC2-9C83-5E4F2FA96BAE</string>
		<key>PayloadVersion</key>
		<integer>1</integer>
	</dict>
</plist>

**Comment by mthielemann** [comment]
@Emod94 Unfortunately you did not add exactly the code I provided. Please look at the line `<key>mcx_preference_settings </key>` in your profile. Do you notice something? After fixing this error, the profile worked here as expected.

**Comment by mthielemann** [comment]
BTW: The log messages you posted are just noise. You can ignore them.

**Comment by mthielemann** [comment]
No idea. I used exactly your profile here with Privileges 2 and it works as expected. 🤷🏻‍♂️

**Comment by xdemiansmithx** [comment]
fwiw, I had a similar issue when clients gained to install 2.0.0 and still had 1.x installed. Removing and reinstalling fixed it for my deployment.

**Comment by Emod94** [comment]
> fwiw, I had a similar issue when clients gained to install 2.0.0 and still had 1.x installed. Removing and reinstalling fixed it for my deployment.

I even removed the app completely with the app cleaner and reinstalled it. Unfortunately, the migration was initially taken over by the JAMF app catalog, so I actually don't know if there are any old files from 1.x left. Unfortunately, the documentation for 1.x is also no longer there, so I may still be testing old paths.

**Comment by kevinVodi** [comment]
Per Mac Admins #Privileges slack channel [comment](https://macadmins.slack.com/archives/C0818ED1D4M/p1732561780791099) - the Jamf App installer wasn't using the PKG. They have since pulled it from the App Installer and reverted back to 1.5.4

**Comment by Emod94** [comment]
Hey @kevinVodi , that actually helped! I just joined the Slack channel and found out how the profile has to be set up so that it also works under JAMF. Here is the example that works for me. @mthielemann fyi.

You might want to include this in the documentation.

I also read a message in the channel that JAMF is probably working 
on a rollback until the problem with packaging is resolved.

Thank you all for the support!

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>ExpirationInterval</key>
	<integer>15</integer>
        <key>HideSettingsButton</key>
        <true/>
        <key>HideSettingsFromDockMenu</key>
        <true/>
        <key>RevokePrivilegesAtLogin</key>
        <true/>
        <key>RequireAuthentication</key>
        <true/>
        <key>AllowCLIBiometricAuthentication</key>
        <true/>
</dict>
</plist>
```
