### ISSUE TITLE
Issue with LimitToGroup in 2.0

### ISSUE THREAD

**Issue by black-erik** [SAP/macOS-enterprise-privileges#133]
We're deploying two key/value pairs via a configuration profile. the ExpirationInterval is working with 2.0 and we were previously using DockToggleMaxTimeout. LimitToGroup doesn't seem to be working on 2.0 (running on macOS 15.1.1). When trying to elevate, the "Request Privileges" button is grayed out. If I revert back to 1.5.4, everything works as expected.

![Screenshot 2024-11-25 at 12 44 35 PM](https://github.com/user-attachments/assets/44f8b7f8-0732-438d-b63f-1fad7174d28c)

**Comment by mthielemann** [comment]
@black-erik Unfortunately I cannot reproduce this on my end. Any chance you upgraded to v2 using the Jamf App Catalog?
