### ISSUE TITLE
[Privileges 2] [Enhancement] Help Button Configuration Options

### ISSUE THREAD

**Issue by rougegoat** [SAP/macOS-enterprise-privileges#134]
We've deployed Privileges 2.0.0 to our test group with an updated configuration.  One thing we've heard back from them is that the Help button on the Request/Revoke Administrator Rights prompt directs users to the GitHub page for the macOS Enterprise Privileges page.  That's fine for IT testers, but for end users that points them to seek help elsewhere.

Would it be possible to add a few settings to configure that Help button?  Something like the existing `HideSettingsButton` would be good start, but it'd be great to be able to point it to a specific URL so the user contacts their IT support rather than the developers of this application.

**Comment by mthielemann** [comment]
This is scheduled for version 2.1.

**Comment by mthielemann** [comment]
@rougegoat Could you please test with the [Privileges 2.1 Public Beta](https://github.com/SAP/macOS-enterprise-privileges/discussions/141)? Thanks.

**Comment by rougegoat** [comment]
I can confirm both the `HideHelpButton` and `HelpButtonCustomURL` work as expected and fully address this enhancement request.
