### ISSUE TITLE
[Privileges 2] - Allow Ability to customise instruction text

### ISSUE THREAD

**Issue by nheffern** [SAP/macOS-enterprise-privileges#137]
When elevating a standard text is displayed:

`You are currently a standard user. If you would you like to request administrator privileges, please enter the reason you need to be elevated to administer this computer in the text field below. Administrator privileges expire in 10 minutes.`

It would be nice to customise this text. For example we would like to add a notice that reasons are audited, or similar other customisation.

**Comment by mthielemann** [comment]
@nheffern We received a similar request for version 1.x and discussed it in the team years ago. In the end we decided not to implement it for usability and security reasons. I think we offer a highly customizable product, especially with version 2, but if you have needs in your environment that require even more customization, please feel free to create your own fork and make the necessary changes. Thanks.
