### ISSUE TITLE
Enhancement - Webhook Data - Machine Information Options

### ISSUE THREAD

**Issue by amyers22** [SAP/macOS-enterprise-privileges#138]
Currently, when using the `RemoteLogging` with a `webook` the `machine` information that is sent is pulled from the computers hardware UUID. 
`{
  "admin": true,
  "expires": "2024-11-27T19:45:19Z",
  "machine": "02F40AAA-B82A-59C6-BEFE-F09643D3B0CC",
  "reason": "Terminal Commands",
  "timestamp": "2024-11-27T19:35:19Z",
  "user": "testuser"
}`
It would be useful to allow this to be the computername or a variable of choice to allow for easier identification of the device that is elevating privileges.

https://github.com/SAP/macOS-enterprise-privileges/blob/main/source/PrivilegesAgent/Classes/MTWebhook.m#L56

**Comment by mthielemann** [comment]
Version 2.1 will get a new profile key `WebhookCustomData` which allows you to pass a dictionary to the webhook:

```
<key>WebhookCustomData</key>
<dict>
   <key>serial</key>
   <string>$SERIALNUMBER</string>
   <key>name</key>
   <string>$COMPUTERNAME</string>
</dict>
```

This will then appear in the json as `custom_data` like this:

```
{
   "admin":true,
   "custom_data": {
      "name":"My Mac",
      "serial":"XYZ1234567"
   },
   "expires":"2024-11-28T07:40:59Z",
   "machine":"E60E8CCB-32F1-4495-A436-BD1939C2BC32",
   "reason":"",
   "timestamp":"2024-11-28T07:20:59Z",
   "user":"testuser"
}
```

**Comment by mthielemann** [comment]
@amyers22 Could you please test with the [Privileges 2.1 Public Beta](https://github.com/SAP/macOS-enterprise-privileges/discussions/141)? Thanks.

**Comment by amyers22** [comment]
No luck so far. This is what I have set and the profile reflects the `$COMPUTERNAME` and `$USERNAME` in the local profile, but the webhook data is as it was in 1.0.
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>ReasonPresetList</key>
	<array>
		<dict>
			<key>default</key>
			<string>Install Software</string>
		</dict>
		<dict>
			<key>default</key>
			<string>Install macOS Updates</string>
		</dict>
		<dict>
			<key>default</key>
			<string>Terminal Commands</string>
		</dict>
	</array>
        <key>WebhookCustomData</key>
        <dict>
		<key>serial</key>
		<string>$SERIALNUMBER</string>
		<key>name</key>
		<string>$COMPUTERNAME</string>
	</dict>
	<key>ReasonRequired</key>
	<true/>
	<key>RequireAuthentication</key>
	<true/>
	<key>HideSettingsButton</key>
	<true/>
	<key>HideSettingsFromDockMenu</key>
	<true/>
	<key>RevokePrivilegesAtLogin</key>
	<true/>
        <key>ExpirationInterval</key>
	<integer>10</integer>
        <key>RemoteLogging</key>
	<dict>
		<key>ServerType</key>
		<string>webhook</string>
		<key>ServerAddress</key>
		<string>https://webhook.site/#######-######-#####-####</string>
	</dict>
</dict>
</plist>`
I am running Privileges 2.1.0.1877

**Comment by amyers22** [comment]
Figured out my previous issue and it was with the positioning of the `WebhookCustomData` in the profile. Adjusted and seeing expected results. Thanks for the quick turn around on this!
