### ISSUE TITLE
App is converting the admin accounts without configuration 

### ISSUE THREAD

**Issue by praveenlnrs** [SAP/macOS-enterprise-privileges#139]
We used the Privileges app before but stopped using it a while ago. We removed the configuration profile that manages the app but the Privileges app itself was still on the devices. 

Admin accounts were converted to standard accounts when the Privileges app was updated to 2.0 even though there was no configuration profile to manage it which impacted our users.

I think the new version is configured to convert the admin account if no configuration is present. I know I should have removed the app along with configuration but I am sure many organizations still have it somewhere without noticing.

 Can this behaviour of converting admin accounts if none of the configurations is present be changed?

**Comment by mthielemann** [comment]
Actually this never happened before and I am unable to reproduce it on my end. Privileges does not automatically remove admin rights after installation. Can you send me additional information that allows me to reproduce it on my end? Thanks.

**Comment by breisig** [comment]
I am having the similar issue. I setup a fresh MacOS install (15.1.1) which the first account created is an admin account and then I create a secondary account which is also an admin account. If I install Privileges v2.0 app on the first account, open it and, sign out and then sign back in to the first or secondary account, it automatically converts the accounts from admin to standard on login. [Which is a pain]

**Comment by mthielemann** [comment]
@breisig Did you use our installer package? Did you change the default configuration or do you have any configuration profiles for Privileges installed?

**Comment by mthielemann** [comment]
I now tried twice what @breisig did:

1. Installed a fresh 15.1.1 with (of course) an admin account. 
2. Installed the Privileges package from GitHub.
3. Logged out from the admin account.
4. Logged in again.

And I still have admin rights as expected. Anything else I can try to reproduce it on my end? Thanks.

**Comment by breisig** [comment]
I just tried it again on another Macbook Air running MacOS 14.7.1 and its still happening.
- Erase HD  and re-install a fresh MacOS install
- Created the initial admin account and signed in.
- Opened Safari and downloaded + install Privileges_2.0.0.pkg file [ https://github.com/SAP/macOS-enterprise-privileges/releases/download/2.0.0/Privileges_2.0.0.pkg ]
- Once finished installing, log off the admin account and sign back in again.
- Check the users account status and its now shows my admin account has been demoted to 'Standard' user.

**Comment by mthielemann** [comment]
How did you upgrade? Using the Jamf App Catalog or the package we provide on GitHub?

**Comment by praveenlnrs** [comment]
@mthielemann The 2.1 beta package fixed the issue on my device!

**Comment by breisig** [comment]
@mthielemann It looks like 2.1 beta package fixed the issue for me too.
