### ISSUE TITLE
PrivilegesCLI Touch ID support

### ISSUE THREAD

**Issue by chaoyangnz** [SAP/macOS-enterprise-privileges#140]
any plan to support Touch ID for PrivilegesCLI?

**Comment by mthielemann** [comment]
As of version 2 this is the case.

**Comment by chaoyangnz** [comment]
Hi @mthielemann 
is there any setting I need? as I only see password prompt, not Touch ID when I run
`PrivilegesCLI --add`

**Comment by mthielemann** [comment]
You need to set `AllowCLIBiometricAuthentication` to `true`. This information can also be found in the [wiki](https://github.com/SAP/macOS-enterprise-privileges/wiki/Managing-Privileges).
