### ISSUE TITLE
STANDARD ACCOUNT 

### ISSUE THREAD

**Issue by sdgr8-214** [SAP/macOS-enterprise-privileges#145]
i just recently deleted the app and when i tried to install something i noticed my account has been switched from admin to standard… is there anything i can do i’m on a 2018 mac mini ventura 13.7.1
![Screenshot 2024-12-03 at 11 16 39 PM](https://github.com/user-attachments/assets/21746cb5-5977-4862-bc27-1b0b31d0a6e0)

**Comment by mthielemann** [comment]
I wonder how you could delete the app without being an admin user. If there's no other account on the system, you could try to boot your Mac in recovery mode and add your user to admin group there using Terminal. Or you could delete the file `/var/db/.AppleSetupDone` while in recovery mode and then restart the machine and create a new admin user using the Setup Assistant.
