### ISSUE TITLE
Enhancement - possibility to show only dropdown menu for reason

### ISSUE THREAD

**Issue by hachirotahoshino** [SAP/macOS-enterprise-privileges#147]
Possibility for reason window to only show dropdown menu without text (or textbox only appearing if reason « other » chosen?)

![IMG_0951](https://github.com/user-attachments/assets/436de03d-4f69-4859-998c-7115449ed612)

it is possible to have only text box but not only dropdown for now.

![IMG_0952](https://github.com/user-attachments/assets/a5b54df6-4d7f-4090-98d6-ddea13621ee8)

**Comment by mthielemann** [comment]
As we cannot change the size of the alert while it is shown, we could only hide the text field and this looks a bit weird. So this is unfortunately not possible.
