### ISSUE TITLE
Reason Preset List pop-up menu includes a single key/string only

### ISSUE THREAD

**Issue by amirghaliusa** [SAP/macOS-enterprise-privileges#149]
I used the "ReasonPresetList" key and I included a few reasons but only one shows up in the pop-up menu. I tested this in Privileges 2.0 and with the latest beta version 2.1.0b1877 and I get the same results.
<img width="286" alt="Screenshot 2024-12-09 at 1 06 28 PM" src="https://github.com/user-attachments/assets/aa8774ee-9d52-4d8b-9ff4-d92805754f35">
![Screenshot 2024-12-09 at 1 19 29 PM](https://github.com/user-attachments/assets/65779666-e100-4921-b56f-118e6d5b06c9)

**Comment by mthielemann** [comment]
Yes, with your configuration it shows only one string. Please see the documentation in the wiki. It shows how it should look like. You need one dictionary per entry and not one dictionary with all the entries.

**Comment by amirghaliusa** [comment]
@mthielemann Thank you, this was an oversight on my part! It's appearing fine now.
