### ISSUE TITLE
LimitToUser doesn't work if NSUserName is not lowercase

### ISSUE THREAD

**Issue by vc5047** [SAP/macOS-enterprise-privileges#15]
https://github.com/SAP/macOS-enterprise-privileges/blob/4ab3d190cc827f059e3779a5a09d2921c71b4459/source/Privileges/AppDelegate.m#L370

In an environment where the NSUserName value is not all lowercase, the LimitToUser feature doesn't work, because the input from the config profile automatically gets lower-cased. The case normalization would need to happen on both sides being compared, or better, should do a case-insensitive comparison. Something like:
`(limitToUser && !([limitToUser caseInsensitiveCompare:_currentUser] == NSOrderedSame))`

I wasn't able to test above, due to issues with the linking in the Xcode project I encountered.

**Comment by mthielemann** [comment]
Thanks. This will be fixed in the next release of Privileges.

**Comment by vc5047** [comment]
Thanks, Marc! Great to hear!
