### ISSUE TITLE
Admin Revoked at 1st Login

### ISSUE THREAD

**Issue by dfbills** [SAP/macOS-enterprise-privileges#150]
After updating to Privileges 2.0, I have a few test systems where the primary user seems to have lost admin rights after 1st login by default. Has anyone else seen this behavior? I haven't had a chance to try to isolate the issue, but I did observe it triggered on the two machines I’ve tested so far.  This surely can’t be the intention of this new feature!

On one of these machines, I've been unsuccessful in recovering. Looks like the old tricks of using recovery mode to resetpassword in Terminal or nuking the .AppleSetupDone file have all been removed or patched away. Before I wipe it out, I was curious if there were any newer tricks which might allow me to re-acquire admin on my primary 101 user. It's been a few years since I played with this!

**Comment by mthielemann** [comment]
This is a known issue of version 2.0 which will be fixed in 2.1. You can use the prerelease version of 2.1 to test it in your environment.

**Comment by dfbills** [comment]
@mthielemann That's a pretty serious bug.  I'm curious, is there any way to recover?

**Comment by mthielemann** [comment]
Just use Privileges to request admin rights that never expire and if you got admin rights, uninstall Privileges.

**Comment by dfbills** [comment]
It prompts me for an admin user, rather than granting limited admin rights.  Pretty serious bug if you ask me as it has caused me to completely wipe two test machines.

**Comment by mthielemann** [comment]
Privileges never asks you to authenticate as an admin user (except during installation). No idea what's going on in your environment but this is not the normal behavior.
