### ISSUE TITLE
Feature Request: Add a machine identifier like serial number to the JSON sent with the webhook

### ISSUE THREAD

**Issue by everetteallen** [SAP/macOS-enterprise-privileges#151]
It is often valuable when using a SEIM like Splunk to report on what device the privilege elevation occurred on.  Adding some unique device identifier like Serial Number to the JSON values sent with the web hook would complete the picture.
Maybe ideally this value could come from  the  configuration profile so Apple variables like %SerialNumber% (https://support.apple.com/en-au/guide/profile-manager/mdm53kqu8903/mac)or Jamf variables like $COMPUTERNAME(https://learn.jamf.com/en-US/bundle/jamf-pro-documentation-current/page/Computer_Configuration_Profiles.html)  could be used. 
Thanks for your consideration.

**Comment by mthielemann** [comment]
@everetteallen Please check the request from [issue #138](https://github.com/SAP/macOS-enterprise-privileges/issues/138). I think this is what you are looking for.
