### ISSUE TITLE
Feature Request: Support HEC "event" field in WebHook JSON

### ISSUE THREAD

**Issue by everetteallen** [SAP/macOS-enterprise-privileges#153]
We would like to send data directly to our Cribl and/or Splunk service using HTTP Event Collector (HEC) but the JSON sent must include the "event" field and it can not be part of the custom webhook data.
See https://docs.cribl.io/stream/4.0/sources-splunk-hec/
So in curl testing this works:
curl -k "https://your.cribl.your.domain:xxx/services/collector/event?token=xxxxx" -d '{"event":"privilege.sap", "admin":true, "custom_data": {"serial":"XYZ1234567"}, "expires":"2024-11-28T07:40:59Z", "machine":"E60E8CCB-32F1-4495-A436-XXXXXXXX", "reason":" what ever", "timestamp":"2024-11-28T07:20:59Z", "user":"testuser"}'

I did try adding event to the custom_data (like "custom_data": {"event:"privileges.sap", "serial":"XYZ1234567"}) but that gives Error "malformed HEC event"

Please consider adding support for HEC required event field in the WebHook data.  
Thanks!

**Comment by mthielemann** [comment]
Would it be ok to have 2 static event types? One `corp.sap.privileges.granted` and `corp.sap.privileges.revoked`?

**Comment by everetteallen** [comment]
So just did a curl test against our servers and it allowed both values.  So ok with me.

**Comment by mthielemann** [comment]
Ok. This should be testable in next week's beta.

**Comment by everetteallen** [comment]
Awesome Thanks!!

**Comment by mthielemann** [comment]
@everetteallen Please test with [Privileges_2.1.0b1925.pkg.zip](https://github.com/user-attachments/files/18186308/Privileges_2.1.0b1925.pkg.zip). Thanks.

**Comment by everetteallen** [comment]
Works with HEC type Event as expected.  I see both corp.sap.privileges.granted and corp.sap.privileges.revoked as expected.
Next step is to test with custom_data as soon as I can work out the Jamf JSON template
