### ISSUE TITLE
FR: Require Justification to Renew Privs - v.2.1

### ISSUE THREAD

**Issue by tonyyo11** [SAP/macOS-enterprise-privileges#159]
**Contextual Setup:**
`ReasonRequired`: TRUE
`RequireAuthentication`: FALSE
`AllowPrivilegeRenewal`: TRUE

**Behavior:**
After the `ExpirationInterval` nears its end, users are presented with a macOS notification asking if they want to renew their privileges. User's can select Renew as often as they deem necessary.

**Feature Request:**
Administrators should be able, via MDM Configuration, to set a `ReasonRequiredToRenew` key so that users must justify why they are continuing to remain as an admin. Their justification may have changed since the initial elevation, which should be recorded within the logging to audit whether someone is endlessly staying as admin and why.

**Comment by mthielemann** [comment]
The idea behind that feature was to give users an easy way to renew their rights. If you have to enter a reason each time, this is somewhat contrary to the initial idea. Perhaps you should then consider deactivating the renewal completely.

**Comment by tonyyo11** [comment]
I do not believe that it should be each and every renewal. My thought process was - if you as an end user are constantly renewing over and over and over again, for whatever reason – after a certain point the admin should be able to require you to be prompted for a reason. 
Or a max renewal before reason/justification is required is more along the lines of what I was thinking. 

I agree on the concept of an easy way to renew, but I think of the ability to endlessly renew and remain as admin on a singular justification.
Hopefully that makes sense.

**Comment by mthielemann** [comment]
In general, it would certainly make sense to define a maximum number of renewals. However, as the user then has admin rights, it is relatively difficult or even impossible to enforce this in the end. Any process that would track something like this can be terminated by an admin. Every file in which something like this would be written can be deleted by an admin.

**Comment by tonyyo11** [comment]
Good point there. Didn’t think that through. Thank you for entertaining my thought process!!
