### ISSUE TITLE
App doesn't work anymore since Catalina 10.15.x

### ISSUE THREAD

**Issue by eici** [SAP/macOS-enterprise-privileges#20]
The App still works on a factory reset Mac with Catalina 10.15.1 

After updating to 10.15.7 the following functionality is missing:
 - Taskbar icon stays always green
 - Badge with minutes is not visible
 - All the timeout settings are not honored and are not working anymore
 - Basically you can just manually switch between admin/normal with invoking the app

This is also true for all Big Sur Versions and for the latest Monterey

Are there any plans to fix this?

**Comment by rtrouton** [comment]
Make sure you're using the latest release. It has been tested and verified to work on macOS Sierra through macOS Monterey:

https://github.com/SAP/macOS-enterprise-privileges/releases/latest

**Comment by eici** [comment]
![image](https://user-images.githubusercontent.com/38024/140067013-8f225a7b-9122-42e0-a346-e4b73902efd4.png)

We are using the latest Version, please see the attached Screenshot.
Can you please reopen the issue?

**Comment by rtrouton** [comment]
We use Privileges 1.5.2 every single day in our Mac environment and we only support the shipping OS, which was macOS Big Sur and is now macOS Monterey. The problems you're experiencing are not appearing in our environment. This is not a product issue.

I would suggest that something is not configured correctly on your end. Specifically, I would recommend making sure that the helper app is installed and loaded correctly.

For deployment, I would recommend building an installer package using the process described in this blog post:

https://derflounder.wordpress.com/2019/03/20/building-an-installer-package-for-privileges-app/

**Comment by aleksozerov** [comment]
I am seeing similar issue on BigSir but in reverse, once privileges are granted the icon stay yellow and never times out.  Followed these instructions above.

**Comment by rtrouton** [comment]
If the issue being reported is that the default behavior of clicking on the dock icon does not give you time-limited admin, that is a separate issue. Please refer to the FAQ:

```
By default, is there a time limit on the admin rights granted by Privileges?

No. Admin rights are granted until some process (like running Privileges again) takes them away.
```

https://github.com/SAP/macOS-enterprise-privileges/wiki/Frequently-Asked-Questions#by-default-is-there-a-time-limit-on-the-admin-rights-granted-by-privileges


```
Can I set Privileges to give me administrator rights for a defined amount of time?

Yes. You can use the Toggle Privileges option on the dock icon to get admin rights for a set amount of time (the default amount is 20 minutes.)
```

https://github.com/SAP/macOS-enterprise-privileges/wiki/Frequently-Asked-Questions#can-i-set-privileges-to-give-me-administrator-rights-for-a-defined-amount-of-time

The only way to get time-limited admin is to use the `Toggle Privileges` option on the dock icon. Time-limited admin is not available otherwise from the Privileges app.

**Comment by eici** [comment]
> The only way to get time-limited admin is to use the `Toggle Privileges` option on the dock icon. Time-limited admin is not available otherwise from the Privileges app.

Thank you very much for talking the time to answer. I think i understood this all correctly and as stated above it works, as you are describing it, on a fresh catalina mac. It dosn't work on all the macs with newer versions.

On the Catalina 10.15.1 i can use the "Toogle Privileges" Menu, everything works.

On a fresh installed Big Sur, Monterey (or updated Catalina): There isn't a "Toogle Privileges" menu-item on the dock icon!

![image](https://user-images.githubusercontent.com/38024/140087282-df6263da-e719-4ac9-919a-34671257134d.png)

> I would suggest that something is not configured correctly on your end. Specifically, I would recommend making sure that the helper app is installed and loaded correctly.

I would be very happy to check! Can you point me in any direction? As i said the Mac is a fresh install, no MDM, no Profile. Is there any log i can check?

**Comment by aleksozerov** [comment]
In my case,  I do see Toggle Privileges but it's grayed out but the stting for Toggle Timeout is set by default to 15 mins through DockToggleTimeout.mobileconfig as you can see in the attachment.  I don't see a countdown and it never locks. 
![Screen Shot 2021-11-03 at 11 11 31 AM](https://user-images.githubusercontent.com/22893361/140089200-400f194a-94e3-4b42-80ad-a6194401c304.png)
![Screen Shot 2021-11-03 at 11 18 13 AM](https://user-images.githubusercontent.com/22893361/140089204-b8ffccc2-ad09-4c3f-998c-e224453bff19.png)
![Screen Shot 2021-11-03 at 11 19 28 AM](https://user-images.githubusercontent.com/22893361/140089436-da48657e-cba0-4cde-83ff-610a27f62031.png)

**Comment by rtrouton** [comment]
This issue is closed. I will no longer be responding in this thread.
