### ISSUE TITLE
Universal app build

### ISSUE THREAD

**Issue by elyscape** [SAP/macOS-enterprise-privileges#22]
Could we get a Universal build of Privileges? It would be nice to have this run natively on Macs that use Apple Silicon.

**Comment by rtrouton** [comment]
Privileges 1.5.2 is a Universal app. 
![Screen Shot 2021-11-09 at 12 13 30 PM](https://user-images.githubusercontent.com/618055/140972512-9b1be5c5-6f0b-4ae7-97ed-70980510e390.png)
