### ISSUE TITLE
[Feature Request] - Time Limit for Users Launching the App

### ISSUE THREAD

**Issue by cpressland** [SAP/macOS-enterprise-privileges#25]
Hello,

We're new to Privileges, I've written a small installer here: https://github.com/binkhq/jamf_scripts/blob/master/privileges.sh which has successfully installed this on my test laptop and written a small Config Profile with only the following settings:

```
  <dict>
    <key>DockToggleTimeout</key>
    <integer>2</integer>
  </dict>
```

This is deployed via Jamf and works great when right clicking the Application on the Dock and selecting "Toggle privileges". 

However, when launching the app and selecting "Request privileges" the user is granted Admin rights indefinitely. Ideally we'd have a configuration option to prevent this from happening and always use a timer, or even just prevent that button from being clicked, forcing users to use the dock mechanism. Any advice on how we can achieve our goal of only having Admin rights for a small period of time?

**Comment by MrCooki** [comment]
I have noticed that is also the case for privileges cli. If `/Applications/Privileges.app/Contents/Resources/PrivilegesCLI --add` is used it will grant admin rights indefinitely.

**Comment by jasontally** [comment]
Yea, I'm quite sure that SAP's security team, and whoever else thinks this helps them out on security, is still on that martini lunch plan.

Really? By default, I click the button one time and I'm root for life? How the hell dose that help security.

Insecure by default is just an excuse to be insecure.

I had really high hopes that this project would improve security on Mac's for the enterprise. The more I follow it, the more I think it's responsible for really bad things.

**Comment by grahampugh** [comment]
@jasontally the user is only root until next login/restart.

**Comment by cpressland** [comment]
@grahampugh - our testing shows that users do not get demoted after a reboot. But I will test this again on the off chance I missed something. If you can share anything specific about your setup that might be helpful to the discussion here I'd really appreciate it.

My solution to this to keep our SecOps team @MrCooki happy was to have a Jamf Policy execute at startup that always removes the user from the Administrators group.

**Comment by grahampugh** [comment]
If you are using Jamf you can also restrict the Privileges binary, which prevents double-clicking the app but still allows the toggle option. 

Or, you can create a LaunchAgent that monitors for a change in the administrators group and runs a demotion script X minutes later. 

I do agree that it would be a nice addition to the app's functionality though, rather than to have to workaround it. But I guess SAP have no need for this functionality and it is ultimately built for their own needs.

**Comment by cpressland** [comment]
@grahampugh well, I'm no Objective-C developer, but any companion scripts I write to uplift the base functionality described here I'll be sure to open source and link in this issue.

**Comment by rtrouton** [comment]
There is an example LaunchAgent available which demotes the user logging in to being a standard user:

[https://github.com/SAP/macOS-enterprise-privileges/tree/main/sample_launchagent](https://github.com/SAP/macOS-enterprise-privileges/tree/main/sample_launchagent)
