### ISSUE TITLE
DockToggleTimeOut

### ISSUE THREAD

**Issue by ImJustPhil** [SAP/macOS-enterprise-privileges#26]
Hi all,

*NB- I'm not a Dev so my jargon might not be clear cut,

Apologies if this is glaringly obvious, but I'm hitting my head against a brick wall here. I have been tasked with onboarding MacOS devices via JAMF and can across this app to help with temporary elevated permissions.

The config is working apart from the DockToggleTimeOut/MaxTimeOut items.

To my understanding, once the user requests admin privileges, after "x" amount of time, the user will demoted back to a standard user and will need to request again. As a test i have set it to be 5mins, however after 20mins to satisfy the MaxTimeOut, the account is still Admin?

Anyone else able to explain this? or am i just interpreting the functionally wrong.

best,
Phil

**Comment by ImJustPhil** [comment]
@aleksozerov - that makes so much sense! I will give that a try

Thank you for the super quick response. Ill post my findings

**Comment by ImJustPhil** [comment]
@aleksozerov this did indeed work when when removing both the "ReasonRequired" & "RequireAuthentication" features. so for that THANK YOU!

A question to any audience would be that this seems sort of pointless, having to instruct users to long press and app and select the "Toggle Privileges" option as opposed to the intuitive click on app. Then also having the "RequireReason" and "RequireAuthentication" disabled, which would in our environment be more desirable, but at the loss of a timeout and need to reboot for permissions to revert.

Anyone got around this at all?

**Comment by grahampugh** [comment]
This script will cause the admin rights to be removed after a set period regardless of how the app is launched:

https://github.com/eth-its/autopkg-mac-recipes-yaml/blob/main/Scripts/Privileges-postinstall.sh

It's designed to work in Jamf Pro, hence the duration is set with "Parameter 4" ($4). You could just change that to a fixed value, or switch to $1 if launching the script in another way..

**Comment by ImJustPhil** [comment]
@grahampugh many thank for this. I will give this a go!
