### ISSUE TITLE
[Feature Request] Schematized reason

### ISSUE THREAD

**Issue by recabarren** [SAP/macOS-enterprise-privileges#27]
One feature that may be very useful in some cases is to have schematized reasons for privilege elevation.

Maybe have a list of default reasons in a config file which would be customizable at deploy time?

Then, modify the app so that it shows a drop down menu with the pre-defined reasons and maybe an "other" option that allows free form like it is now?

**Comment by mthielemann** [comment]
Sounds like a good idea. This feature will be included in the upcoming version 1.5.3 of Privileges.

**Comment by rtrouton** [comment]
[Addressed as part of Privileges 1.5.3](https://github.com/SAP/macOS-enterprise-privileges/releases/tag/1.5.3).
