### ISSUE TITLE
EnforcePrivileges applies to all users when LimitToGroup is also used

### ISSUE THREAD

**Issue by neilmartin83** [SAP/macOS-enterprise-privileges#28]
Using the following profile payload:

```
<key>EnforcePrivileges</key>
<string>user</string>
<key>LimitToGroup</key>
<string>privilegesUsers</string>
```

The intention is to ensure all users in the group `privilegesUsers` are kept as standard users/demoted if they are admins.

Expected behaviour is that local admin users who are not in this group would be unaffected by the `EnforcePrivileges` preference.

Observed behaviour is that local admin users who are not in the group `privilegedUsers` are also being demoted to standard users by Privileges when `EnforcedPrivileges` is set to `user`.

Is this intended behaviour or would this be a bug/unintended behaviour?

If this is intended behaviour could I please request a feature to either:

- Only have EnforcePrivileges affect users defined in `LimitToUser` or `LimitToGroup` - ignoring any users outside that scope.
- Have new preferences to exclude a local user or group from being affected by Privileges, including the `EnforcePrivileges` preference at all. For example, it could be called `IgnoreUser` and `IgnoreGroup`.

Thank you!

**Comment by mthielemann** [comment]
Thanks for bringing this to our attention. The issue will be fixed in the next release of Privileges.

**Comment by mthielemann** [comment]
The idea behind `EnforcePrivileges` is to **enforce certain privileges for all users**. If you set `EnforcePrivileges` privileges cannot be changed anymore using the app.

`LimitToGroup` **limits the usage of the app to a specific user group**. So some users on the system can change their privileges using the app and others can't. As `EnforcePrivileges` takes precedence over `LimitToGroup`, the `LimitToGroup` setting has actually no effect in this case.

If I understand correctly you want to enforce standard user rights for all accounts except those in the group `privilegedUsers`. Is this correct?

**Comment by rtrouton** [comment]
Closing for lack of response.
