### ISSUE TITLE
Installing Helper Tool Requires Administrator Rights

### ISSUE THREAD

**Issue by silentArtifact** [SAP/macOS-enterprise-privileges#30]
Is there any way that the helper tool that attempts to install on first run could be installed automatically when Privileges is installed?

**Comment by grahampugh** [comment]
@silentArtifact see https://derflounder.wordpress.com/2022/04/20/building-a-privileges-installer-package-using-autopkg/

**Comment by silentArtifact** [comment]
Oh, this is perfect! Thanks!
