### ISSUE TITLE
[Feature Request] - Custom approval workflow plugin

### ISSUE THREAD

**Issue by cs2889** [SAP/macOS-enterprise-privileges#32]
It would be a nice feature to add a custom plug-in that would allow you to insert your own approval process before permissions are changed for the user.  This will allow enterprises to inject whatever approval process by returning yeah or nay before implementation of additional privileges.

**Comment by rtrouton** [comment]
Could you provide more details on what you're thinking of? The reason I'm asking is that different enterprises will have different ideas for workflow approval processes, so this could be a very large ask.

**Comment by mthielemann** [comment]
We have reviewed this request and determined that this is not something we will be implementing in the foreseeable future.
