### ISSUE TITLE
[Feature Request] - Deployment ready releases

### ISSUE THREAD

**Issue by Bretterteig** [SAP/macOS-enterprise-privileges#34]
It would be awesome if the releases of this tool would have an option for preinstalling the helper tool in a standardised way. This is helpful if the users receiving the app are already standard users or have been previously demoted.

These are two scenarios I could think of:

- Distribute the app in .pkg format
- Add a CLI option post-install tasks (e.g. like Xcode `/usr/bin/xcodebuild -runFirstLaunch`)

This would make future deployments easier to maintain and more resilient to errors and changes.

**Comment by rtrouton** [comment]
There is an option using a tool called [AutoPkg](https://github.com/autopkg/autopkg) to generate an installer package for Privileges. For more information on this, please see the link below:

https://derflounder.wordpress.com/2022/04/20/building-a-privileges-installer-package-using-autopkg/

**Comment by Bretterteig** [comment]
I am already using AutoPkg with your recipe and this has been fine. Just wondering why this is not part of the official release. 

It would make life easier for small businesses, tech aware users who update them self and the like to have a "it just works" type of installer.

I am writing this because I have been in an "unrecoverable" state where I couldn't grant myself admin privileges anymore.
Previously I updated Privileges manually by replacing the app and got demoted by external means without starting the app after update.

**Comment by rtrouton** [comment]
We're satisfied with the AutoPkg method for generating an installer package for Privileges.

**Comment by rougegoat** [comment]
This may be worth revisiting.  Jamf lists the SAP Privileges app as one of the titles they will distribute through their [App Installers feature](https://docs.jamf.com/jamf-app-catalog/App_Installers_Software_Titles.html).  It's unclear if they're building the pkg to deploy or if they're downloading directly from the Media Source URL they list.  The latter would be a direct link to the Privileges.zip hosted here that is missing the pre/post-install scripts from that DerFlounder link above.  That is an issue on Jamfs end, but it may be good to head it off by adding the deployment ready pkg anyway.
