### ISSUE TITLE
[Feature Request] - Local Authentication with the PrivilegesCLI

### ISSUE THREAD

**Issue by geoffrepoli** [SAP/macOS-enterprise-privileges#35]
When the `RequireAuthentication` setting is enabled, PrivilegesCLI will prompt the user to enter their password by passing it through stdin when using the `--add` switch. 

As I am interested, and I'm sure others are as well, in creating custom workflows for temporary, on-demand privilege escalation, the only way to pass the user's credentials to authentication presently is through insecure AppleScript prompts that then passes it in cleartext to the command line. 

I'm curious if it's possible (and if so - would love to have this feature realized) to leverage [LAPolicy.deviceOwnerAuthentication](https://developer.apple.com/documentation/localauthentication/lapolicy/deviceownerauthentication) within the CLI tool to create a prompt identical to the one that appears when requesting privileges through the Privileges GUI

**Comment by mthielemann** [comment]
This will be implemented in Privileges 2.0.0, which will be available later this year.
