### ISSUE TITLE
Both GUI and CLI stuck but nothing happening

### ISSUE THREAD

**Issue by seenukarthi** [SAP/macOS-enterprise-privileges#39]
Both GUI and CLI just hangs and nothing happening on macOS 12.4. There are no errors and messages. 

How to check what is happening?

macOS version: 12.4
Laptop: MacBook Pro (14-inch, 2021)
Chip: Apple M1 Pro

**Comment by rtrouton** [comment]
This may be an issue with how it was deployed. One way to sort this out is to do the following:

1. Uninstall Privileges using the [uninstallation instructions.](https://github.com/SAP/macOS-enterprise-privileges/wiki/Uninstallation)
2. Reboot
3. Build a Privileges installer package using the [AutoPkg](https://autopkg.github.io/autopkg/) tool. Instructions on how to do this are linked below:

https://derflounder.wordpress.com/2022/04/20/building-a-privileges-installer-package-using-autopkg/

4. Install Privileges on a test Mac using the AutoPkg-built installer package.
5. See if the problem persists.

**Comment by Bretterteig** [comment]
I am experiencing this as well since version 1.5.3. After the reasons dialog it just gets "stuck". I am using your autopkg recipe through munki. I have a 100% failure rate with this :(

**Comment by rtrouton** [comment]
I didn't write the .munki recipe and don't use Munki myself, so I'm not sure what to tell you in this case. What I would recommend is verifying that the actual installer package works, using the steps described above:

1. Uninstall Privileges using the [uninstallation instructions.](https://github.com/SAP/macOS-enterprise-privileges/wiki/Uninstallation)
2. Reboot
3. Build a Privileges installer package using the [AutoPkg](https://autopkg.github.io/autopkg/) tool. Instructions on how to do this are linked below:

https://derflounder.wordpress.com/2022/04/20/building-a-privileges-installer-package-using-autopkg/

4. Install Privileges on a test Mac using the AutoPkg-built installer package.
5. See if the problem persists.

**Comment by rtrouton** [comment]
Since I don't have the knowledge of how to fix the `.munki` recipe for AutoPkg, I've now disabled it. A deprecation warning has been added to explain the situation:

```
This recipe is now non-functional. Please remove it from your list of recipes. The com.github.rtrouton.munki.privileges recipe appears to have problems as of Privileges 1.5.3. I do not use Munki and I do not have the knowledge necessary to figure out why this is happening, so I am deprecating this recipe and adding a StopProcessingIf step to prevent it from running. Hopefully someone with more expertise in this area is able to write a .munki recipe for Privileges which works correctly.
```
