### ISSUE TITLE
Privileges not removed after timeout

### ISSUE THREAD

**Issue by moobyfr** [SAP/macOS-enterprise-privileges#40]
I use version 1.5.3 (installed with autopkg), on macos 12.5, and deployed several settings with JAMF(authentification, reason, and timeout)
the timeout isn't working, after the delay, I'm still being admin, verified with Privileges --status

**Comment by grahampugh** [comment]
@moobyfr how did you invoke the timeout? (just making sure you know that the timeout only applies if you right-click and select "toggle privileges"...)

**Comment by rtrouton** [comment]
Please see the Privileges FAQ, as this topic is covered:

[By default, is there a time limit on the admin rights granted by Privileges?](https://github.com/SAP/macOS-enterprise-privileges/wiki/Frequently-Asked-Questions#by-default-is-there-a-time-limit-on-the-admin-rights-granted-by-privileges)

No. Admin rights are granted until some process (like running Privileges again) takes them away.

[Can I set Privileges to give me administrator rights for a defined amount of time?](https://github.com/SAP/macOS-enterprise-privileges/wiki/Frequently-Asked-Questions#can-i-set-privileges-to-give-me-administrator-rights-for-a-defined-amount-of-time)

Yes. You can use the **Toggle Privileges** option on the dock icon to get admin rights for a set amount of time (the default amount is 20 minutes.)

**Comment by rtrouton** [comment]
For more information, please see this blog post:

https://derflounder.wordpress.com/2022/07/22/privileges-app-and-time-limited-admin

**Comment by salihzett** [comment]
i have the same issue, installed previous version, but still the same. also macOS 12.5

**Comment by moobyfr** [comment]
As rtrouton's comment, removal of access is not part of the program. The blog entry is much better than the FAQ, I'll propose a FAQ update on this point, but I'm in vacation for the time being

**Comment by salihzett** [comment]
yes but it is also strange without a config profile. The color of the icon is not changing as expected. but sure, I will check the blog.

**Comment by peterlewis** [comment]
I have come across `install_privileges_checker.zsh by @kandji-inc which is available [here](https://github.com/kandji-inc/support/tree/main/PrivilegesChecker).

Deployed as-is, it makes use of `DockToggleTimeout` to enforce a switch back to Standard privileges after a set period of time. My experience is that it can simply be run as a script, following installation of Privileges.app.

**Comment by grahampugh** [comment]
@peterlewis this script is more efficient than the Kandji one, because instead of running a script every 30 seconds, the LaunchDaemon actually monitors for changes to the admins file and only runs the script when there's a change: https://github.com/eth-its/autopkg-mac-recipes-yaml/blob/main/Scripts_for_Installers/Privileges-postinstall.sh

**Comment by peterlewis** [comment]
@grahampugh Nice! Thanks for that, Graham, I like it! :) Only in the testing stages at the moment, so can easily change course, but what I do like about the script by @kandji-inc is the ability to use the timeout from the Configuration Profile as it makes trivial changing the value when/where it is required to do so.

**Comment by dash4385** [comment]
I believe that if the ToggleTimeout is set that should be the default behavior whether you hit toggle or run the app. or at least have the option to configure it that way. I always want the admin rights to expire and never want a user to blanket to have them. I rather than have to use the app more often or request permanent admin rights.
