### ISSUE TITLE
macOS 13 Beta 4 - GUI Prompt not showing up

### ISSUE THREAD

**Issue by remixyz** [SAP/macOS-enterprise-privileges#41]

**Comment by rtrouton** [comment]
I'm able to reproduce and I've reported this issue to the developer. `Toggle privileges` and the `PrivilegesCLI` command line tool appear to work normally.

There haven't been any changes to Privileges, so this would appear to the result of some change Apple made between Ventura beta 3 and beta 4.

**Comment by Lotusshaney** [comment]
I can confirm the same behaviour.

**Comment by rtrouton** [comment]
In our testing, enabling Stage Manager causes the dialog windows to re-appear.

**Comment by vc5047** [comment]
I'm able to replicate the Stage Manager behavior.

**Comment by rtrouton** [comment]
It looks like updating to macOS Ventura beta 5 fixes the issue.

**Comment by rmckellar** [comment]
I'm on beta 5 and cannot get the dialog window, even when logging out and back in. Same issue happens on Monterey 12.5.

**Comment by Lotusshaney** [comment]
The dialog windows DO appear on all of my beta 5 test Mac's

**Comment by rtrouton** [comment]
@rmckellar This may be an issue with how it was deployed. One way to sort this out is to do the following:

1. Uninstall Privileges using the [uninstallation instructions.](https://github.com/SAP/macOS-enterprise-privileges/wiki/Uninstallation)
2. Reboot
3. Build a Privileges installer package using the [AutoPkg](https://autopkg.github.io/autopkg/) tool. Instructions on how to do this are linked below:

https://derflounder.wordpress.com/2022/04/20/building-a-privileges-installer-package-using-autopkg/

4. Install Privileges on a test Mac using the AutoPkg-built installer package.
5. See if the problem persists.

**Comment by rmckellar** [comment]
Thanks Rich! I'll definitely give that a shot!

**Comment by rmckellar** [comment]
Still no luck on my Ventura Beta 5 machine. My guess it there's something else conflicting. Works on 12.4 and 12.5. Time to dig! :P
