### ISSUE TITLE
App getting stuck

### ISSUE THREAD

**Issue by Bretterteig** [SAP/macOS-enterprise-privileges#50]
Hey everyone. I am experiencing the same issues as #39.

I build the package via autopkg and deploy via munki from rtrouton recipes. 

It seems it gets stuck after the reason interface. Could this be due to the reasons preset list change?

1.5.2 (Same recipe. Same deployment) works flawless.

The LD is loaded and the privileged helper is in place. There are 0 logs written for corp.sap.privileges

**Comment by rtrouton** [comment]
I didn't write the .munki recipe and don't use Munki myself, so I'm not sure what to tell you in this case. What I would recommend is verifying that the actual installer package works, using the steps below:

1. Uninstall Privileges using the [uninstallation instructions.](https://github.com/SAP/macOS-enterprise-privileges/wiki/Uninstallation)
2. Reboot
3. Build a Privileges installer package using the [AutoPkg](https://autopkg.github.io/autopkg/) tool. Instructions on how to do this are linked below:

https://derflounder.wordpress.com/2022/04/20/building-a-privileges-installer-package-using-autopkg/

4. Install Privileges on a test Mac using the AutoPkg-built installer package.
5. See if the problem persists.

**Comment by rtrouton** [comment]
Since I don't have the knowledge of how to fix the `.munki` recipe for AutoPkg, I've now disabled it. A deprecation warning has been added to explain the situation:

```
This recipe is now non-functional. Please remove it from your list of recipes. The com.github.rtrouton.munki.privileges recipe appears to have problems as of Privileges 1.5.3. I do not use Munki and I do not have the knowledge necessary to figure out why this is happening, so I am deprecating this recipe and adding a StopProcessingIf step to prevent it from running. Hopefully someone with more expertise in this area is able to write a .munki recipe for Privileges which works correctly.
```

**Comment by Bretterteig** [comment]
After some digging I might have found the culprit. 

Gatekeeper seems to be blocking the execution of the privileged helper.
