### ISSUE TITLE
Error sending privileges to Microsoft Intune

### ISSUE THREAD

**Issue by jonasTMoreira** [SAP/macOS-enterprise-privileges#51]
Good afternoon. I'm trying to push Privileges to Microsoft's Intune.
PKG file works perfectly fine when installed on Mac directly.
When we sent via Munki it worked.
But when we send privileges to Microsoft Intune it doesn't work. Has anyone uploaded privileges to Intune? Can you help?

Note: For the tests above I used 2 types of pkg. I generated them using the links provided by the Privileges developer himself:

https://derflounder.wordpress.com/2022/04/20/building-a-privileges-installer-package-using-autopkg/

https://derflounder.wordpress.com/2019/03/20/building-an-installer-package-for-privileges-app/

Has anyone managed to send privileges in Microsoft's Intune? Can anyone help?

**Comment by jonasTMoreira** [comment]
Can anyone help?

**Comment by JohanLeirnes** [comment]
Hi,

The package has to be signed with a developer ID and also notarized before intune will install it.

It also requires some information inside the PKG to be defined:
see info:
https://docs.microsoft.com/en-us/troubleshoot/mem/intune/macos-lob-apps-not-deployed

I suggest you install them with a script if they are signed this should work (not tested):

```bash
#!/bin/bash

# Variables
log="/var/log/privileges-app.log"
package="ftps://*****"
ftpuser="*******\*******"

# Start logging
exec 1>> $log 2>&1

# Begin Script body
curl -u $ftpuser $package -o /tmp/privlieges.zip
unzip -o /tmp/privlieges.zip -d /tmp/
sudo installer -pkg /tmp/Privileges.pkg -target /Applications/
```

Issue next is to set do the setup process of the app preferably silently without user-interaction.
