### ISSUE TITLE
No admin accounts left

### ISSUE THREAD

**Issue by EUROJOB** [SAP/macOS-enterprise-privileges#52]
I noticed the app actually make the admin a standard user when I check user in system preferences. Then I deleted the app and the system did not have an admin anymore. And as a standard user I could not change it to an admin anymore. And I could not change it back to admin without the app which was deleted.  
Of course I did this on purpose but is’t kinda strange situation you can end up with if someone deletes the app while the only admin is demoted.

**Comment by rtrouton** [comment]
All I can say is "Don't do that."

**Comment by grahampugh** [comment]
Assuming you are deploying Privileges with a management solution (as it is surely only designed for enterprise environments), you can just deploy it again.
