### ISSUE TITLE
Admin Not Removed after Timeout when using Single Click

### ISSUE THREAD

**Issue by kbareis** [SAP/macOS-enterprise-privileges#57]
I am deploying Privileges 1.5.3 build with AutoPKG and uploaded to Jamf. I am also configuring via Plist to set DockToggleTimeout (shared below). What I am seeing is if I right click on the dock icon for Privileges, and toggle admin, the timer and badge show up as expected and I am demoted to standard user. I have also experimented with single clicking on the Privileges app and the experience is different. When I single click, a dialog appears and asks me if I would like to request admin privileges. If I use this method, the user is never demoted. I expected this to function the same as if I right clicked and chose toggle. Is this expected behavior or am I doing something wrong?

`pref domain: corp.sap.privileges`

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>DockToggleTimeout</key>
    <integer>1</integer>
  </dict>
</plist>
```

**Comment by rtrouton** [comment]
Please see the blog post linked below:

https://derflounder.wordpress.com/2022/07/22/privileges-app-and-time-limited-admin/

**Comment by ooshnoo** [comment]
this is really stupid and backwards way of implementing this software.  If admin want to limit the admin access time, one should NOT have to use a "secondary" function in order to achieve it.

**Comment by rtrouton** [comment]
Noted.
