### ISSUE TITLE
super user

### ISSUE THREAD

**Issue by fredd3** [SAP/macOS-enterprise-privileges#60]
It would be nice to have a mode to elevate privileges to super user since admin sudo no longer permits any access to /system/library folders since 10.15. writing to /user/library doesn't always cut it, especially for developers wanting to test out their code.

**Comment by rtrouton** [comment]
There are no super user privileges which can address the issue you're reporting. macOS Catalina 10.15.x introduced the concept of moving the system software (including anything in `/System`) to a read-only volume: 

https://support.apple.com/HT210650

As of macOS Big Sur 11.x, this read-only system volume is cryptographically sealed and alterations to it result in the OS not booting:

https://support.apple.com/guide/security/secd698747c9/web
