### ISSUE TITLE
Privileges not opening on Ventura 13.2

### ISSUE THREAD

**Issue by Gitchiel** [SAP/macOS-enterprise-privileges#61]
Hi,
I have a config which was working with Monterey, deploying this recipe: com.github.rtrouton.pkg.privileges (so the package "Privileges-1.5.3.pkg" was pulled with AutoPkgr in June 2022 and working fine at that time). Now, if I deploy the same package on Ventura 13.2 Macs with Jamf, along with the config, Privileges.app won't open anymore. 
If I check console I'm finding the following entry: "-[PersistentAppsSupport applicationQuit:] | for app:Privileges, _appTrackingState = 2".
No notification / error displayed, when trying to start the app; no difference, whether trying to start with a user-account with elevated or normal privileges.
Any ideas? Do I have to add a pppc entry for Ventura, which wasn't necessary for Monterey? I checked the documentation, didn't find anything relevant there so far. 
Thanks in advance.

**Comment by rtrouton** [comment]
What is the configuration? Can you share it?

Also, does Privileges work when not using the configuration?

**Comment by Gitchiel** [comment]
Yes, so I've only the key LimitToUser defined (xml below); but I do have the PrivilegesDemoter script running with some settings... Which works without issues, warns or ignores depending on the user, as defined in the script - so I wasn't expecting this to be the reason. 
I'll set up a testmachine without any configuration, and then gradually add 1st the normal config, then Demoter script etc., to check this more in detail tomorrow, will post an update after. 
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>LimitToUser</key>
    <string>tadmin</string>
  </dict>
</plist>`

**Comment by Gitchiel** [comment]
Ok, deployed just the app, without any settings, and it's not opening either. Have a mcOS 13.0.1 machine, where it's working fine; guess it might be a 13.2 issue, or is it working without issues for others?
Also tested replacing the app with the one, downloaded straight from the latest release here, doesn't make a difference...

**Comment by rtrouton** [comment]
My shop has around 16,000 Macs running both Privileges 1.5.3 and macOS 13.2, so if there was an issue with the app not launching on macOS 13.2, we likely would be experiencing the same issue that you're seeing on at least some of them. We're not, so I suspect there's something else for the root cause.

If you haven't yet, you may want to build a new Privileges 1.5.3 installer and test that.

**Comment by Gitchiel** [comment]
Ok, deployed just the app, without any settings, and it's not opening either. Have a mcOS 13.0.1 machine, where it's working fine; guess it might be a 13.2 issue, or is it working without issues for others?
Also tested replacing the app with the one, downloaded straight from the latest release here, doesn't make a difference...

**Comment by Gitchiel** [comment]
Looks like it's a config issue after all; haven't got the time to check it in detail, in the middle of a rollout, but it's working with 13.2 now... Therefore closing this, thanks for the feedback.
