### ISSUE TITLE
Question about notification and not full admin rights

### ISSUE THREAD

**Issue by Tugamuc** [SAP/macOS-enterprise-privileges#62]
Hello, first of all thanks for the great tool..
I still have 2 topics, maybe someone has it and can answer it for me.
1. It is possible for the client to send a request, e.g. to Slack and I as admin give him the rights??
2. I it possible if the user has his admin rights to change the options that can create a new user. Since if the normal user has his Temp Admin rights, he can also create a new user account with Admin rights.

Maybe someone has the same problem and can give me a few tips. Currently we're using Filewave for deplymen.. if that matters... we don't have Active Directory

**Comment by rtrouton** [comment]
Both of those topics are outside of the scope of the Privileges app. The first topic is not something we're planning to  address at this time. The second topic is better directed at Apple, as it concerns how admin rights work on macOS.
