### ISSUE TITLE
Is it possible to rollback new users?

### ISSUE THREAD

**Issue by Tugamuc** [SAP/macOS-enterprise-privileges#63]
Hello everyone
Unfortunately, I noticed that if the standard user gets his admin rights via "Privileges", he can use it to create a new user and set him as admin.
After "Privileges" has timed out and the user is standard again, the user he created is still there. Unfortunately this is not good.
Is there a possibility to rollback so that if the user creates a new user, the tool deletes the new user after the timeout or only gives him standard rights

**Comment by rtrouton** [comment]
That's outside the scope of what Privileges does, which is to grant or remove admin privileges to the currently logged-in account on a Mac. What the user chooses to do with those admin rights would need to be handled outside of Privileges.

**Comment by Tugamuc** [comment]
Do you have any ideas how I can best solve this?

**Comment by rtrouton** [comment]
What are your security requirements for this situation? In short, why is granting admin to the logged in user OK, but having them create additional users not OK?

**Comment by rtrouton** [comment]
OK. Do you have a management tool for managing the Macs in your environment? If so, one idea is that you could have it monitor to see if anyone aside from the logged-in user has admin rights. If there's another account with admin rights, remove that account's admin rights. That other account would still exist but not have admin.

I am not able to provide technical guidance with this, only the idea.

**Comment by Tugamuc** [comment]
Thanks in advance I think that the tool I'm using can't do it properly hahaha I use FILEWAVE but I'll keep looking...please keep it up
