### ISSUE TITLE
No "Toggle Privileges" option in Docker Icon

### ISSUE THREAD

**Issue by tianjun-orby** [SAP/macOS-enterprise-privileges#64]
![Screen Shot 2023-03-08 at 10 07 39 AM](https://user-images.githubusercontent.com/123766823/223794802-4de6201f-5d84-470b-9b33-7dab6175e2f7.png)

Hi, I can't find the "Toggle Privileges" option in the Docker Icon, as shown by the screenshot.  The device is a MacBook Pro 2021 with Apple M1 Pro chip and macOS Monterey (version 12.6.3)

**Comment by fortiko** [comment]
Same as happened with the icon mentioned in https://github.com/SAP/macOS-enterprise-privileges/issues/38#issuecomment-1732029704 the entry "Toggle Privileges" disappeared when I upgraded to 1.5.4 via Homebrew. Reverting via installing the original 1.5.3 PKG fixes it, even without rebooting. Happy to help with logs to get to the bottom of this.

**Comment by mthielemann** [comment]
It's not reproducible on our end. Have this running on about 40.000 Macs and never saw this issue.

**Comment by fortiko** [comment]
I'm glad to hear that @mthielemann 

Just upgraded to 1.5.4 via homebrew, and the exact same still happens for me: no "Toggle Privileges" option in the Dock Icon, only the standard "Options >", "Show Recent" and "Open" are available in the context menu.

What's more, the icon is green, and yet, when I run privileges as a normal app (not via the context menu), after confirming the "Remove privileges" dialog, nothing happens. No adding/removing of privileges happens. ¯\_(ツ)_/¯

**Comment by mthielemann** [comment]
What happens if you install Privileges using the installer package we provide?

**Comment by mthielemann** [comment]
Sorry, my mistake. We plan to provide an installer package with the next release of Privileges. For now, please use the following instructions: https://derflounder.wordpress.com/2019/03/20/building-an-installer-package-for-privileges-app
