### ISSUE TITLE
[Feature Request] Encryption & Auth for Remote Logging

### ISSUE THREAD

**Issue by ghost** [SAP/macOS-enterprise-privileges#65]
Hey, it isn't currently possible to ship logs from endpoints that run this app to a syslog server in a secure way. I've outlined three things that could benefit greatly for enterprise grade deployments:

1. Certificate based auth to ensure only authorised clients can send logs to syslog server.
2. Logs are sent over plaintext, need syslog over TLS. 
3. Make TCP default protocol.

**Comment by vgrenkov** [comment]
Ran into this issue as well, as a work around, ended up writing a script that uploads logs to paper trail (can be adjusted to any server pretty easily). Then I have a custom command running in MDM that executes every x minutes.

`#!/bin/bash
set -e
LOG_FILE="/var/log/privileges.log"
LAST_READ_FILE="/var/tmp/last_read_line"
HOSTNAME=$(hostname)

# Check if the last read line file exists, if not, create it
if [ ! -f "$LAST_READ_FILE" ]; then
    echo "0" > "$LAST_READ_FILE"
fi

# Read the last read line number
LAST_READ_LINE=$(cat "$LAST_READ_FILE")

# Get the total number of lines in the log file
TOTAL_LINES=$(wc -l < "$LOG_FILE")

# Check if new lines have been added
if [ "$TOTAL_LINES" -gt "$LAST_READ_LINE" ]; then
    # Calculate the number of lines to read
    LINES_TO_READ=$((TOTAL_LINES - LAST_READ_LINE))

    # Read new lines and prepare payload
    PAYLOAD=$(tail -n "$LINES_TO_READ" "$LOG_FILE" | sed "s/^/$HOSTNAME: /" | sed ':a;N;$!ba;s/\n/\\n/g')
    # Upload the data
    curl -u :TOKEN -H "Content-Type: text/plain" -d "$PAYLOAD" https://logs.collector.solarwinds.com/v1/logs
    # Update the last read line number
    echo "$TOTAL_LINES" > "$LAST_READ_FILE"
fi

`

**Comment by mthielemann** [comment]
Support for syslog over TLS will be implemented in Privileges 2.0.0, which will be available later this year. Besides of this, the new version will not support UDP anymore.
