### ISSUE TITLE
Privileges trying to install a helper tool while I'm a standard user.

### ISSUE THREAD

**Issue by kimo-supremo** [SAP/macOS-enterprise-privileges#68]
My college manages my laptop. Privilege is trying to install a helper tool while I'm a standard user. I cannot install a helper tool without admin privileges. please help 
![image](https://user-images.githubusercontent.com/70135155/233853361-daf6183b-bac1-45e8-9ed2-2733e824540f.png)

**Comment by swolosin** [comment]
You need to reach out to whomever admins your laptop. There’s a section in
the wiki and a post install script that will resolve this issue. All these
things need to be done by your admin.

**Comment by kimo-supremo** [comment]
is there no way to disable the helper installer just for 1 minute to get my privileges and then install it?

**Comment by rvera53** [comment]
Can you tell us where on the wiki we can find this? I have searched but couldn't find the post-install script.
Thank you.

**Comment by kimo-supremo** [comment]
no clue where I'd find it in the wiki but here it is in my app. I fixed it by contacting my admin but then the issue happened again so I had to contact the admin again to fix it. 
![image](https://user-images.githubusercontent.com/70135155/235751343-6a1d66e8-ab6b-4ae7-8ffa-5b2953acb5b6.png)

**Comment by rvera53** [comment]
I'm the admin trying to get my users this app, but the helper is giving me some issues. I created a post-install script that runs the CLI command to add the user but when removing the privileges from the app the pop up comes again.

I'm not sure what to do about the helper anymore :/

**Comment by shannonpasto** [comment]
You can find some info on how to install the helper tool at https://derflounder.wordpress.com/2019/03/20/building-an-installer-package-for-privileges-app/ It's mostly about packaging the app but you should be able to work what goes where

**Comment by ivan-odintsov** [comment]
I am admin on my own PC and I am the only user of it. I use the app to be safe. But now my Mac is locked with this helper thing on basic user privileges. What should I do to unlock, except reinstall the OS?
