### ISSUE TITLE
[Feature Request] Time limited admin in main app.

### ISSUE THREAD

**Issue by ntauthy** [SAP/macOS-enterprise-privileges#69]
Can a feature be implemented to have the admin privileges demote back to standard user with respect to the "Dock Toggle Timeout"? 
I can't see any users taking the time to set themselves back to standard manually. I love how this app works other than that. The "Request privileges" button should respect the Toggle Timeout (or similar config option) which we (as mac admins) should be able to set in the config profile. 

I know theres another demoter script but that's just one more layer of complexity that would be SO nice to have built into Privileges. 

<img width="476" alt="Screenshot_5_8_23__2_58_PM" src="https://user-images.githubusercontent.com/7943655/236909911-e2c58773-6c43-42a6-b373-0b3184eaf0ff.png">

**Comment by dortmund50** [comment]
+ 1

**Comment by shannonpasto** [comment]
+1

**Comment by robatjamf** [comment]
+1

**Comment by marckerr** [comment]
This should be the default functionality without complicating the setup with customized scripts like those developed by Kanji. Regardless of how the app is launched it should respect timeout limits. Users don't typically right click a Dock icon, they usually launch apps from the Dock. For Privileges, launching the app essentially makes them a admin forever and defeats the point of a time limited admin. I would prefer users be admin always but org policy says no so we have to use tools like Privileges for these functions. We could use the much more simple Make Me Admin script from Jamf but there are convenience features of utilities like Privileges that we'd like to use.

**Comment by mjsalinger** [comment]
+1

**Comment by chrisrosa** [comment]
+1

**Comment by hachirotahoshino** [comment]
+1

**Comment by otigraoken** [comment]
+1

**Comment by mthielemann** [comment]
This will be implemented in Privileges 2.0.0, which will be available later this year.
