### ISSUE TITLE
[Feature Request] - customise the dialog

### ISSUE THREAD

**Issue by shannonpasto** [SAP/macOS-enterprise-privileges#70]
Hi.

It would be great to be able to customise the dialog that is presented to the user when they open the app. Perhaps something in the preference domain so it can be deployed via MDM. Both heading and message.

![Screenshot 2023-05-12 at 09 03 20](https://github.com/SAP/macOS-enterprise-privileges/assets/25423644/19f2b2b8-47c7-4847-a423-34af94791fe9)

Thanks,
Shannon

**Comment by mthielemann** [comment]
We have reviewed this request and determined that this is not something we will be implementing in the foreseeable future.
