### ISSUE TITLE
"killall Dock" clears the timer allowing for infinite admin

### ISSUE THREAD

**Issue by timjd4** [SAP/macOS-enterprise-privileges#73]
Currently have Privileges configured to use the dock toggle function with a 20min limit set via profile.  The app itself can't be launched because it's blocked by Jamf restricted software.

Everything works as expected unless the Dock process is killed via terminal or anything that relaunches the Dock.  The badge timer goes away and the user is admin unless they toggle it off themselves.

**Comment by timjd4** [comment]
I have a similar thing in place where Jamf demotes via PrivilegesCLI at login but we have a few apps in Self Service that add items to the dock and when the dock restarts the icon remains orange with admin privs but no timer.

**Comment by timjd4** [comment]
Does that mean the issue has been fixed or can't be fixed?  Looks like the same behaviour for v1.5.4

**Comment by mthielemann** [comment]
This behavior will change in a future version of Privileges.
