### ISSUE TITLE
"Login Window ..." toggle functionality of dock menu item not working as expected

### ISSUE THREAD

**Issue by crgundersen** [SAP/macOS-enterprise-privileges#74]
Per the wiki/frequently asked questions: "The Login Window toggle option returns you to the Login Window without logging you out." In my testing of Privileges.app 1.5.3 w/ macOS Ventura 13.3.1, I'm not finding success w/ the "Login Window ..." toggle functionality in the Privileges dock menu item. While the "Lock Screen" (and other) toggles have desired behavior, Login Window does not have any effect in my tests. Hopefully I'm not misunderstanding it's use case. Thanks much!

**Comment by tauruskarthick** [comment]
Count me in. Me too having same behaviour on Ventura 13.5..

**Comment by mthielemann** [comment]
This will be fixed in Privileges 2.0.0, which will be available later this year.
