### ISSUE TITLE
Stays unlocked after reboot if you unlock and reboot

### ISSUE THREAD

**Issue by CountryNerd** [SAP/macOS-enterprise-privileges#75]
If you unlock privileges then reboot it will reboot unlocked and stay unlocked till locked again.

**Comment by rtrouton** [comment]
Correct. Please see the `By default, is there a time limit on the admin rights granted by Privileges?` question in the `Frequently Asked Questions` wiki page:

https://github.com/SAP/macOS-enterprise-privileges/wiki/Frequently-Asked-Questions#by-default-is-there-a-time-limit-on-the-admin-rights-granted-by-privileges
