### ISSUE TITLE
[Feature Request] - Touch ID Support when requiring the user to enter the password

### ISSUE THREAD

**Issue by jalucia** [SAP/macOS-enterprise-privileges#76]
Would love to have the option of configuring TouchID instead of having them type in the password if the user is required to enter their password on elevation request.

**Comment by mthielemann** [comment]
This is already the case.

**Comment by Skittlesbucket** [comment]
+1 on fingerprint support on the CLI!

**Comment by wfeiring** [comment]
Another +1!

**Comment by sampl3x** [comment]
+1

**Comment by Cliffback** [comment]
+1

**Comment by 1nu** [comment]
+1 for having this for CLI as well.

**Comment by mthielemann** [comment]
This is a [duplicate](https://github.com/SAP/macOS-enterprise-privileges/issues/35)
