### ISSUE TITLE
so like...how do we install it

### ISSUE THREAD

**Issue by pixelpandacreative** [SAP/macOS-enterprise-privileges#78]
source code, nothing else, except instructions that say to add it to the Applications folders, which we cant because theres no application to be added lol

**Comment by rtrouton** [comment]
Every version of Privileges has an accompanying GitHub Release: 

https://github.com/SAP/macOS-enterprise-privileges/releases

Attached to each Release, there’s a `Privileges.zip` file containing a copy of that version’s Privileges app. The latest Release is available via this link:

https://github.com/SAP/macOS-enterprise-privileges/releases/latest
