### ISSUE TITLE
The "Dock Tile Timeout" setting not applied in macOS 14 Sonoma beta 4

### ISSUE THREAD

**Issue by sakahn** [SAP/macOS-enterprise-privileges#79]
In macOS 14 Sonoma beta 4, "Toggle privileges" from the Dock menu (Control + Click) always toggles the privileges after 20 minutes, no matter what value I choose from Settings --> Dock Tile Timeout menu.

**Comment by mthielemann** [comment]
Yes, that's an issue we are currently working on with Apple. Unfortunately it's nothing we can fix on our end but we are confident that the problem will be fixed by Apple.

**Comment by randommacguy** [comment]
I have same issue with Ventura 13.5.1 is this expected?

I tried manually setting the time out and doing through profile but it just doesn't seem to bring user back to standard

**Comment by MatimusPrime** [comment]
I'm seeing this as well no timers are working since 13.5.1 and I just updated to 13.6 and it's still not working.

**Comment by clevelandbread** [comment]
I am on 13.5.2 and I am seeing issues persists. I do not see anything that indicates DockToggleTimeout.

**Comment by phastier** [comment]
Hello, I have the same issue. The TImeOut (distributed through a Configuration profile) is not enforced anymore. This is a serious problem.

**Comment by hachirotahoshino** [comment]
Hi, on sonoma 14.3 i have the same issue.
