### ISSUE TITLE
Make show desktop optional

### ISSUE THREAD

**Issue by hreeder** [SAP/macOS-enterprise-privileges#80]
Hi Folks,

I'd like to request that this section be made configurable.

https://github.com/SAP/macOS-enterprise-privileges/blob/5ab148e55a4aa2ca44974e3c6c64d4dba72e192e/source/Privileges/AppDelegate.m#L170-L173

At the moment I have to use the "Toggle Privileges" option from the right click menu from the taskbar item to avoid the animation on both open and close of the dialog.

**Comment by mthielemann** [comment]
This is a [duplicate](https://github.com/SAP/macOS-enterprise-privileges/issues/58)
