### ISSUE TITLE
PrivilegesXPS - Helper Tool Update

### ISSUE THREAD

**Issue by CaputoDavide93** [SAP/macOS-enterprise-privileges#82]
How can we prevent and fix the request of admin rights for PrivilegesXPS, looks like that an update of the HELPER TOOL is necessery but not sure why.
![image](https://github.com/SAP/macOS-enterprise-privileges/assets/17005686/85ecc06b-a0dc-4bda-9e98-ccb7bcde974f)

Many thanks!

**Comment by marcelpogorzelski** [comment]
Workaround:
I used the pre- and postinstall scripts from here (modified for Jamf):
https://github.com/autopkg/rtrouton-recipes/tree/master/Privileges/Scripts
Read more here:
https://derflounder.wordpress.com/2019/03/20/building-an-installer-package-for-privileges-app/

**Comment by p-harrison** [comment]
> Workaround:
> I used the pre- and postinstall scripts from here (modified for Jamf):
> https://github.com/autopkg/rtrouton-recipes/tree/master/Privileges/Scripts
> Read more here:
> https://derflounder.wordpress.com/2019/03/20/building-an-installer-package-for-privileges-app/

I’m just working through a Privileges setup in Intune at the moment.  Out of interest did you find a way to deploy the plist (included in the postinstall script) using a JAMF policy/config instead of embedding it in a script like that? I think it would be cleaner, but I’m not sure if that type of MachServices settings can be deployed using MDM.

**Comment by marcelpogorzelski** [comment]
I used the script as is. Just removed the $3 since it's not in a package.

I use heredoc in script for other things as well. That is the easiest way of adding/modifying files with Jamf.

**Comment by marcelpogorzelski** [comment]
I use https://github.com/Installomator/Installomator/blob/main/Installomator.sh to install Privileges.
If you instead make a Package than you should be able to add the MachService directly as a file. You will only need to bootstrap the service with the script.

**Comment by tombea** [comment]
> > Workaround:
> > I used the pre- and postinstall scripts from here (modified for Jamf):
> > https://github.com/autopkg/rtrouton-recipes/tree/master/Privileges/Scripts
> > Read more here:
> > https://derflounder.wordpress.com/2019/03/20/building-an-installer-package-for-privileges-app/
> 
> I’m just working through a Privileges setup in Intune at the moment. Out of interest did you find a way to deploy the plist (included in the postinstall script) using a JAMF policy/config instead of embedding it in a script like that? I think it would be cleaner, but I’m not sure if that type of MachServices settings can be deployed using MDM.

Did you ever solve this with InTune? I have built a package with the pre and post install scripts, and while it appears to install the app fine, and create the Privileged Helper, and launchdaemon plists in all the right places. On the first run after install the user still gets prompted for admin creds to install PrivilegesXPC helper? I can't figure out what I am missing.

**Comment by p-harrison** [comment]
> Did you ever solve this with InTune? I have built a package with the pre and post install scripts, and while it appears to install the app fine, and create the Privileged Helper, and launchdaemon plists in all the right places. On the first run after install the user still gets prompted for admin creds to install PrivilegesXPC helper? I can't figure out what I am missing.

No I didn't manage to solve that issue.  To be honest we ultimately decided it would not be a good idea to deploy Privileges into production as the GitHub project does not seem to be well supported.  For now we continue to use separate local admin accounts pushed to devices via script.

**Comment by rtrouton** [comment]
I’ve noticed that a number of folks have experienced problems with manually building an installer package for Privileges which correctly installs the Privileges app’s helper tool. I don’t know why this is the case, but there is a solution for the issue. Building an installer for Privileges using a tool called AutoPkg consistently delivers a working installer package:

https://derflounder.wordpress.com/2022/04/20/building-a-privileges-installer-package-using-autopkg/

**Comment by p-harrison** [comment]
> I’ve noticed that a number of folks have experienced problems with manually building an installer package for Privileges which correctly installs the Privileges app’s helper tool. I don’t know why this is the case, but there is a solution for the issue. Building an installer for Privileges using a tool called AutoPkg consistently delivers a working installer package:
> 
> https://derflounder.wordpress.com/2022/04/20/building-a-privileges-installer-package-using-autopkg/

It was step 8 that put us off :)
`8. Repeat process as needed for each new version of Privileges.`
