### ISSUE TITLE
We've uninstalled and are now getting a "PrivilegesCLI: permission denied" on all terminals

### ISSUE THREAD

**Issue by ghost** [SAP/macOS-enterprise-privileges#83]
This has impacted a user's account and the local admin account for support on the impacted device. The error appears when we open a new Terminal window. We seem to be getting odd permissions issues/things refusing to run despite the user being in the correct groups and having sudo access.

Is there anything we're missing?

**Comment by TCG-Olly** [comment]
Is this actively supported?
