### ISSUE TITLE
Privileges window appearing behind admin credentials pop up

### ISSUE THREAD

**Issue by svenhopman** [SAP/macOS-enterprise-privileges#84]
It seems there's a bug with the Privileges window not taking focus if a user is not active on the desktop e.g. the user is active on a fullscreen app.  

![image](https://github.com/SAP/macOS-enterprise-privileges/assets/22344666/94e7892c-1b29-4272-88d6-ec977cac3a27)

This issue can be recreated by forcing an admin credentials pop up, moving to another fullscreen app (the admin credentials pop up will remain over the fullscreen app), and then triggering Privileges.  

The expected functionality can be seen if, from a desktop (not a fullscreen app), an admin credentials pop up is forced, then Privileges is triggered.  All other windows are moved aside (including the admin credentials pop up) and Privileges takes focus.

---
A possible related issue is that, when this is performed with an external monitor with both the MacBook screen and the monitor displaying fullscreen apps, Privileges will not take focus at all, requiring the user to manually navigate to the desktop where Privileges appeared.

**Comment by mthielemann** [comment]
This will be fixed in Privileges 2.0.0, which will be available later this year.
