### ISSUE TITLE
PrivilegesCLI Remove not working with RequireAuthentication

### ISSUE THREAD

**Issue by iec-LarsTh** [SAP/macOS-enterprise-privileges#87]
I dont know if this is by design, but when configuring RequireAuthentication via MDM configuration profile the PrivilegesCLI is disabled for the --add and --remove option (macOS 14.1.1) with an error message:

_You cannot use this app to change your privileges because your administrator has restricted the use of this app._

While I understand that this might be by design for the --add option, why is this blocked for removing admin rights as well? The process of removing through Privileges.app does not ask for credentials, so CLI should not as well.

**Comment by mthielemann** [comment]
Removing admin rights should be always possible without entering credentials. This is by design.
