### ISSUE TITLE
PrivilegesCLI add/remove output message

### ISSUE THREAD

**Issue by Jaharmi** [SAP/macOS-enterprise-privileges#89]
PrivilegesCLI’s output when the “add” or “remove” options are used is grammatically awkward in English:

- “User X **has now** admin rights”
- “User X **has now** standard user rights”

It should be:

- “User X **now has** admin rights”
- “User X **now has** standard user rights”

Or, it could also be the following. (This would be somewhat less-useful for parsing/matching against the output.)

- “User X **has** admin rights **now**”
- “User X **has** standard user rights **now**”

English arranges “now” differently in a sentence compared to German’s “jetzt.”

**Comment by mthielemann** [comment]
This will be fixed in Privileges 2.0.0, which will be available later this year.
