### ISSUE TITLE
Demotion not work ?

### ISSUE THREAD

**Issue by bghilardibm** [SAP/macOS-enterprise-privileges#90]
Good morning,
Obviously demotion to standard user is not automatic at the end of the allotted time.
Is this normal or a bug in the app?

**Comment by rtrouton** [comment]
Please see the following entries in the FAQ:

```
By default, is there a time limit on the admin rights granted by Privileges?

No. Admin rights are granted until some process (like running Privileges again) takes them away.
```


https://github.com/SAP/macOS-enterprise-privileges/wiki/Frequently-Asked-Questions#by-default-is-there-a-time-limit-on-the-admin-rights-granted-by-privileges

```
Can I set Privileges to give me administrator rights for a defined amount of time?

Yes. You can use the Toggle Privileges option on the dock icon to get admin rights for a set amount of time (the default amount is 20 minutes.)
```


https://github.com/SAP/macOS-enterprise-privileges/wiki/Frequently-Asked-Questions#can-i-set-privileges-to-give-me-administrator-rights-for-a-defined-amount-of-time
