### ISSUE TITLE
[Feature Request] - Enable logging to a slack channel

### ISSUE THREAD

**Issue by tbcahill** [SAP/macOS-enterprise-privileges#91]
Would it be possible to enhance the remote logging options to include sending promotion requests to Slack? 

Here is an example bash script that could be used:
`
currentTime=$(date +"%d/%b/%Y %H:%M UTC")
loggedInUser=$(scutil <<< "show State:/Users/ConsoleUser" | awk '/Name :/ && ! /loginwindow/ { print $3 }')
deviceSerial=$(system_profiler SPHardwareDataType | awk '/Serial/ {print $4}')
selectedMinutes= #Specify the Duration for promotion 
Justification= #User's reason for promotion

slackChannel="QWERTYUIOP" 
slackToken="Authorization: Bearer xoxb-123456789-123456789-qwertyuiop"  

slackMessage="*Privilege Elevation Request*\n*Timestamp:* $currentTime\n*User:* $loggedInUser\n*Device:* $deviceSerial\n*Duration:* $selectedMinutes minutes\n*Justification:*\n$justification"

curl -H "Content-type: application/json" \
--data '{"channel":"'"$slackChannel"'","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"'"$slackMessage"'"}}]}' \
-H "$slackToken" \
-X POST https://slack.com/api/chat.postMessage`

**Comment by mthielemann** [comment]
We have reviewed this request and determined that this is not something we will be implementing in the foreseeable future.
