### ISSUE TITLE
Firefox can't update automatically, fails to install helper tool?

### ISSUE THREAD

**Issue by ralfbergs** [SAP/macOS-enterprise-privileges#93]
Hi,

our IT are using "Jamf" to manage our Macs. We're currently still on 13.6.3 (ARM64), using Privileges 1.5.4 (1368).

Requesting temp. admin privileges via "Privileges" generally works well. However, I have notorious issues with Firefox being unable to update itself. I always resort to downloading the full package, and then installing it over the existing version, but this is a bit annoying and inconvenient.

At one point during the automatic update process (that fails later) I would get a prompt for elevation, telling me "Firefox is trying to install a new helper tool." I would allow this by supplying my password (elevating my privileges, being an "admin" user), and still the automatic update will fail in the end.

Please find a couple of screenshots attached. I'm using a "Primary Password" to protect the secrets stored in my Firefox profile.

Can you understand from those what my problem might be? Or could you guide me how to find out where the automatic update is failing?

Don't ask me to ask our IT, please. They're very clueless and don't even respond in such cases.

Many thanks in advance for your help.

![Screenshot 2024-01-24 at 07 37 47](https://github.com/SAP/macOS-enterprise-privileges/assets/7198745/afee5341-1aa2-46d4-842c-b582973ef30d)
![Screenshot 2024-01-24 at 07 38 32](https://github.com/SAP/macOS-enterprise-privileges/assets/7198745/c004b94d-f2ec-48ca-b689-27437da02fb2)
![Screenshot 2024-01-24 at 07 38 19](https://github.com/SAP/macOS-enterprise-privileges/assets/7198745/8e103aa1-fa79-4c2f-a863-668ba200964b)
![Screenshot 2024-01-24 at 07 38 01](https://github.com/SAP/macOS-enterprise-privileges/assets/7198745/602612cc-82f3-496d-898a-abbc2c91e479)
![Screenshot 2024-01-24 at 07 37 22](https://github.com/SAP/macOS-enterprise-privileges/assets/7198745/80f03c11-ba78-49f2-b25f-a0692809343d)

**Comment by rtrouton** [comment]
I sympathize with the problem you’re having, but this isn’t a problem caused, or which can be solved, by Privileges.

**Comment by ralfbergs** [comment]
> I sympathize with the problem you’re having but this isn’t a problem caused, or which can be solved, by Privileges.

Thank you for your comment. I have zero understanding of how this tool works, so I'm sorry for raising an issue here.

Could you (with your supposed much better understanding) please hint me towards the most likely root cause? Is it Firefox that "is at fault" here?
