### ISSUE TITLE
bypass actual app lmitation for timeout by using a menu item?

### ISSUE THREAD

**Issue by hachirotahoshino** [SAP/macOS-enterprise-privileges#95]
Hi, i am in the need of a solution to give some users a temporary admin elevation solution, and SAP is great, but not userproof for the "timeout" feature

as clicking the app may create an issue, why not using a menu item to have the "toggle privilege" and the timer?

it would avoid the user misuse of the app button and we would be sure to have privileges going back to what they were.

I know it is a heated subject but i thought it was worth a shot to propose this to go around the actual misuse case.

Thanks for the good work

**Comment by mthielemann** [comment]
We have reviewed this request and determined that this is not something we will be implementing in the foreseeable future.
